### PR TITLE
Issue 2236: replace piwik with matomo

### PR DESCRIPTION
**Pull request by za**
and also (PIWIK with MATOMO)

### CODE REVIEW

**Comment by za** [comment]
@avaris Hmm... I haven't tested this code yet. _Finding out how to test the code..._

**Comment by za** [comment]
BTW @avaris This is the test result:

```
(venv)za@kwazii:03:00:26 (2236-replace-piwik-with-matomo) ~/dev/github/za/pelican$ python -Wd -m unittest discover
.......................................................................................................................s.......................F.F..........................sss...............ss...............F.......................
======================================================================
FAIL: test_simple_prefix (pelican.tests.test_generators.TestGenerator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pelican/tests/test_generators.py", line 156, in test_simple_prefix
    self.assertEqual(expected_path, os.path.dirname(filename))
AssertionError: u'pelican/themes/simple/templates' != '/home/za/dev/github/za/pelican/pelican/themes/simple/templates'

======================================================================
FAIL: test_theme_prefix (pelican.tests.test_generators.TestGenerator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pelican/tests/test_generators.py", line 166, in test_theme_prefix
    self.assertEqual(expected_path, os.path.dirname(filename))
AssertionError: u'pelican/themes/notmyidea/templates' != '/home/za/dev/github/za/pelican/pelican/themes/notmyidea/templates'

======================================================================
FAIL: test_article_with_footnote (pelican.tests.test_readers.MdReaderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pelican/tests/test_readers.py", line 483, in test_article_with_footnote
    self.assertEqual(content, expected_content)
AssertionError: u'<p>This is some content<sup id="fnref:1"><a class="footnote-ref" href="#fn:1"  [truncated]... != u'<p>This is some content<sup id="fnref-1"><a class="footnote-ref" href="#fn-1"> [truncated]...
Diff is 1885 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 231 tests in 8.912s

FAILED (failures=3, skipped=6)
```

I think the first two failed test is not related with the PR.

**Comment by justinmayer** [comment]
I'm starting to wonder whether these kinds of settings should exist in Pelican core. Anyone have any thoughts about that? (cc: @getpelican/reviewers)

**Comment by ivanhercaz** [comment]
> I'm starting to wonder whether these kinds of settings should exist in Pelican core. Anyone have any thoughts about that? (cc: @getpelican/reviewers)

I think this kind of features/settings should be part of a plugin (in this case one dedicated to address the analytics with different services) or be easy to configure in the themes.

**Comment by justinmayer** [comment]
Thank you for the contribution, @za. As I suggested above, rather than renaming these bits, I think it makes more sense to deprecate analytics in Pelican core and relegate them to plugins/themes. So I have removed Piwik from theme and settings docs via e18c9d2c.

**Comment by za** [comment]
Thanks for the notification @justinmayer Sorry, I haven't been able to look at this issue again.

**Pull request closed without merging**
