### PR TITLE
Suppress error messages when PID files cannot be found

### PR DESCRIPTION
**Pull request by PeterMosmans**

### CODE REVIEW

**Comment by iKevinY** [comment]
Maybe we should also `return 1` if the PID files are missing to indicate that something went wrong.

**Comment by PeterMosmans** [comment]
Hi @iKevinY wouldn't that be counter-intuitive ? If the PID files aren't there, then it might be that the server is already shut down. One would expect an 'OK' then: the server has been shut down.

**Comment by iKevinY** [comment]
Ah, yeah that makes sense. It's probably fine to leave it as-in then.

**Comment by justinmayer** [comment]
The develop_server.sh script has been removed in a recent pull request, so this is likely moot at this point. Feel free to let me know if that's not the case.

**Pull request closed without merging**
