### PR TITLE
Add support for Unicode slugs

### PR DESCRIPTION
**Pull request by avaris**
This has two commits for adding the option to use unicode in auto-generated slugs
* Reworks `slugify` and adds the `use_unicode` argument. See commit message for details about what changed and why. Also adds direct tests for `use_unicode`
* Exposes the option in `settings` as `SLUGIFY_USE_UNICODE` (default: `False`), uses it internally, updates docs and adds an indirect test for it. While updating the docs, I also moved the `SLUGIFY_SOURCE` documentation to where the other related settings are.

Fixes #1207

### CODE REVIEW

**Comment by avaris** [comment]
On a slightly related note, `slugify` also has an option for `preserve_case` but this wasn't exposed as a setting. If exposing it sounds beneficial, I can add to this PR.

**Comment by justinmayer** [comment]
@avaris: I think exposing the `preserve_case` setting makes sense. Would you add that to this PR as you suggested?

**Comment by avaris** [comment]
@justinmayer Done :heavy_check_mark:

**Comment by justinmayer** [comment]
Looks great. Many thanks for your work on this! 💯🥇

**Pull request merged**
