### PR TITLE
PTAL: Chinese translation

### PR DESCRIPTION
**Pull request by GeorgeHu6**
Complete the translations of the first two sections

### CODE REVIEW

**Comment by GeorgeHu6** [comment]
@justinmayer I have get all of the translation done. Do I need to do something else so that it can be accepted to official documentation?

**Comment by justinmayer** [comment]
Many thanks for your efforts, George. I am traveling for the next couple of weeks but will endeavor to review this as soon as I possibly can! 😁

**Comment by justinmayer** [comment]
Hi George. The intention is to merge this once we have the opportunity to review. Is there some reason you closed it?

**Comment by GeorgeHu6** [comment]
Sorry for the deleting, I would like to rearrage the translation file in order to make it better. The new request will be pulled in several days.

**Pull request closed without merging**
