### PR TITLE
Add the category to the feed item. Fixes #2556.

### LINKED ISSUE #2556: Category not available on atom feed
I just noticed that, when Pelican generates the atom feed, the category of the post isn't in the feed content.

Searching for the reason, I found this line:

https://github.com/getpelican/pelican/blob/de71f39232947014149436a4205029d3a1b39f3e/pelican/writers.py#L87

Basically, instead of passing the category on the categories field, it passes the tags.

Is there any reason for this behavior than I am not aware of?

Wouldn't be more correct to pass the post category on the categories field, or, at least, to pass the category AND the tags?

### PR DESCRIPTION
**Pull request by mauriciogardini**
Adds the article category as a feed item category.

### CODE REVIEW

**Comment by mauriciogardini** [comment]
This is my first time making a pull request to Github, so correct me if I'm wrong.

The change that I made changed the xml that was generated quite dramatically. I thought that, by making the fix in my second commit that I would solve the problem, but it's bigger than it looks. 

Is the best solution for me to change manually all the pelican/tests/output/custom/feeds/alexis-metaireau.atom.xml file until it is equal to what's being rendered by Travis? Or there is another way of treating a situation like this, that has many changes?

As for the other 2 errors on the build:
- pelican.contents: ERROR: Skipping /home/travis/build/getpelican/pelican/samples/content/another_super_article-fr.rst: could not find information about 'date'
- pelican.contents: ERROR: Skipping /home/travis/build/getpelican/pelican/samples/content/pages/jinja2_template.html: could not find information about 'title'

I see no relation of these errors with my commit. Again, is there anything that I'm missing?

**Comment by avaris** [comment]
@mauriciogardini No, you don't do it manually. See the [here](http://docs.getpelican.com/en/stable/contribute.html#running-the-test-suite) for regenerating outputs.

**Comment by mauriciogardini** [comment]
> @mauriciogardini No, you don't do it manually. See the [here](http://docs.getpelican.com/en/stable/contribute.html#running-the-test-suite) for regenerating outputs.

Thanks for the help, @avaris . It was easier than expected.

Sorry for the silly questions, first time making a pull request to Github and first time making a contribution to pelican.

**Comment by justinmayer** [comment]
Many thanks for the contribution, @mauriciogardini. There were some lines in the changes that looked like line-ending modifications, so I went ahead and re-generated the functional test output via 7bfc70c1538108dfaf1b0cbfc563ee4883bc1f2a and manually merged into `master`.

This feature is included in the just-released [Pelican 4.2](https://github.com/getpelican/pelican/releases/tag/4.2.0). ✨

**Pull request closed without merging**
