### PR TITLE
When truncating, stop parsing the document immediately after finding the last word

### PR DESCRIPTION
**Pull request by andreacorbellini**
This commit makes the `_HTMLWordTruncator` faster by stopping it immediately as soon as the last word is found. This should improve performances for blogs that have many articles.

This is the last PR of this series.

### CODE REVIEW

**Comment by ingwinlu** [comment]
logically looks good.

from a code readability standpoint I would suggest to add the return value as an attribute to the exception (minor details but it is more self describing than `.args[0]`)

**Comment by justinmayer** [comment]
Hi Andrea. Any thoughts on Winlu's suggestion here?

**Comment by andreacorbellini** [comment]
Sorry, I'm busy right now. I will fix it this weekend :)

**Comment by andreacorbellini** [comment]
A bit late, but finally here I am.

**Pull request merged**
