### PR TITLE
add more information to contribution guidelines

### PR DESCRIPTION
**Pull request by oulenz**
I've added some changes to the contribution guidelines that address the 'friction' I experienced when I filed my first pull requests to Pelican, i.e. things that seem logical now that I know, but which could have been clearer.

### CODE REVIEW

**Comment by jorgesumle** [comment]
Probably, we want to update the reference to pep8. See the new package [pycodestyle (formerly called pep8) - Python style guide checker](https://pypi.org/project/pycodestyle/). It was renamed, as you can see in the latest release note (1.7.1 (2017-10-22)):

> Prominently note via warning message that the tool is no longer released as pep8 and will only be fixed in the pycodestyle package

> If you are using PyCharm and are relying on its warnings for PEP8 compliance, note that you have to decrease the line length to 79, since its default is 120.

Notes about particular text editors shouldn't be added, in my opinion. Otherwise, we would have tons of recommendations which will make the text longer to read and less relevant to people who don't use that particular editor.

**Comment by avaris** [comment]
I agree with @jorgesumle about editor-specific notes.

And ` Testing on Python 2 and 3` section seems... odd. Not your change. That whole section. I think it's somewhat outdated :). It should be basically "After making changes run tests on all supported python versions or use `tox`."

PS: Personally, I don't recommend `conda` but, meh, sure.

**Comment by oulenz** [comment]
pep8 -> pycodestyle: changed

PyCharm: made the comment more general, removing specific mention of PyCharm.

Conda: @avaris I don't want to put words in your mouth. :-) Is there something specific about Conda that you would say makes it less suitable for Pelican development?

Python 2/3: I've rewritten that section, please have a look.

**Comment by oulenz** [comment]
@avaris Are you satisfied with the changes so this can be merged?

**Comment by oulenz** [comment]
Thanks, I've squashed the commits so this can be merged.

**Comment by justinmayer** [comment]
Merged via 8ef9d11b. Many thanks to Oliver for the improved documentation and to @ingwinlu, @jorgesumle, and @avaris for reviewing. Much appreciated!

**Pull request closed without merging**
