### PR TITLE
Change periods (...) to ellipsis (…) in post summaries

### PR DESCRIPTION
**Pull request by dhimmel**
Use ellipsis when truncating, for example in `article.summary`.

### CODE REVIEW

**Comment by dhimmel** [comment]
Closing until I fix the test failures.

**Comment by justinmayer** [comment]
Hi Daniel. Thanks for the enhancement. As you probably noticed, any change that affects output will cause functional test failures unless the changes are accompanied by updated functional test output. This is the purpose of the functional tests, of course.  (^_^)  This is covered in more detail in our [testing docs](http://docs.getpelican.com/en/stable/contribute.html#running-the-test-suite).

Also, instead of closing your pull request and then creating a new one, it would be better to add a follow-up commit to the existing PR and then rebase+squash your commits into a single commit. This reduces PR noise/clutter and makes it easier for maintainers to manage the project. So you might consider re-opening this pull request and working within it instead of creating a new one.

**Comment by dhimmel** [comment]
Thanks @justinmayer for the guidance. I'm reopen and work on the pull request.

[Here's a discussion](https://www.drupal.org/node/847608 "Use ellipsis character (…) instead of three dots (...)") going over the merits of the proposed change.

**Comment by justinmayer** [comment]
You may need to rebase on current master, which contains fixes for some unrelated test failures.

**Comment by dhimmel** [comment]
Okay I updated the tests, rebuilt the HTML output, squashed my commits, and rebased to the current master.

All tests pass locally when I run `python -m unittest discover`. It looks like there are still several Travis-CI failures. Not sure exactly what is causing them.

***

The biggest point of confusion for me was regenerating the HTML output as [described here](http://docs.getpelican.com/en/3.6.3/contribute.html#running-the-test-suite). The main issue was that pasting the commands with newlines caused failures. When I switched to running the below commands everything worked:

```shell
LC_ALL=en_US.utf8 pelican -o pelican/tests/output/custom/ -s samples/pelican.conf.py samples/content/
LC_ALL=fr_FR.utf8 pelican -o pelican/tests/output/custom_locale/ -s samples/pelican.conf_FR.py samples/content/
LC_ALL=en_US.utf8 pelican -o pelican/tests/output/basic/ samples/content/
```

**Comment by dhimmel** [comment]
It looks like regenerating the HTML caused some [weird changes](https://github.com/dhimmel/pelican/commit/039c9456890501e1096dabfb2b6435c9b3832a36). @justinmayer, any advice on how to proceed?

**Comment by avaris** [comment]
@dhimmel you don't have French locale (`fr_FR.utf8`) installed on your system. Make sure you have both locales (`en_US.utf8` and `fr_FR.utf8`) and then try regenerating the output.

**Comment by dhimmel** [comment]
Thanks @avaris and @justinmayer. I think the pull request is finally at a point where it can be considered for inclusion.

The biggest struggle I faced was generating the output. In addition to the [snag mentioned above](#issuecomment-186430707), I had to make sure to clear the output directory (`rm -r pelican/tests/output/*`) of extra files that were created when the french local was missing.

**Comment by ingwinlu** [comment]
lgtm

**Comment by justinmayer** [comment]
Many thanks to @dhimmel, @avaris, and @ingwinlu.

**Pull request merged**
