### PR TITLE
apply #1057 to notmyidea

### PR DESCRIPTION
**Pull request by alb-i986**
Add meta tags keywords, description, tags to notmyidea.
See #1057

### CODE REVIEW

**Comment by iKevinY** [comment]
Note that the build failed because you changed the theme templates, but didn't update the "expected output" files. You should be able to avoid having to manually make all of the changes by following the commands described [here](http://docs.getpelican.com/en/3.5.0/contribute.html#running-the-test-suite); pushing a commit with the new output files should result in a passing build.

**Comment by alb-i986** [comment]
Thanks @iKevinY that helped.

```
(pelican)alb@albs-MacBook-Air:~/workspace/pelican (meta-tags-in-notmyidea)$ LC_ALL=en_US.utf8 pelican -o pelican/tests/output/custom/     -s samples/pelican.conf.py samples/content/
ERROR: Skipping pages/jinja2_template.html: could not find information about 'title'
Done: Processed 12 article(s), 1 draft(s) and 3 page(s) in 0.31 seconds.
(pelican)alb@albs-MacBook-Air:~/workspace/pelican (meta-tags-in-notmyidea)$ LC_ALL=fr_FR.utf8 pelican -o pelican/tests/output/custom_locale/     -s samples/pelican.conf_FR.py samples/content/
ERROR: Skipping pages/jinja2_template.html: could not find information about 'title'
Done: Processed 12 article(s), 1 draft(s) and 3 page(s) in 0.35 seconds.
(pelican)alb@albs-MacBook-Air:~/workspace/pelican (meta-tags-in-notmyidea)$ LC_ALL=en_US.utf8 pelican -o pelican/tests/output/basic/     samples/content/
WARNING: LOCALE option doesn't contain a correct value
WARNING: Feeds generated without SITEURL set properly may not be valid
WARNING: No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check http://docs.getpelican.com/en/latest/settings.html#timezone for more information
ERROR: Skipping ./another_super_article-fr.rst: could not find information about 'date'
ERROR: Skipping ./draft_article.rst: could not find information about 'date'
ERROR: Skipping pages/jinja2_template.html: could not find information about 'title'
WARNING: Unable to find `/pictures/Sushi.jpg`, skipping url replacement.
WARNING: Unable to find `/pictures/Sushi_Macro.jpg`, skipping url replacement.
WARNING: Unable to find `/pictures/Fat_Cat.jpg`, skipping url replacement.
Done: Processed 11 article(s), 0 draft(s) and 3 page(s) in 0.22 seconds.
(pelican)alb@albs-MacBook-Air:~/workspace/pelican (meta-tags-in-notmyidea)$ python -m unittest discover
..............................................................................sssssssssssssss.................................................................
----------------------------------------------------------------------
Ran 158 tests in 3.859s

OK (skipped=15)
```

I got some warns and errs from the commands to update the expected output. Is it alright?

**Comment by iKevinY** [comment]
Hmm, I'm not sure if there's supposed to be errors or not when running the third command; someone more familiar might have to comment on this. The Travis build passes now, which I guess bodes well.

Regarding the changes to the template themselves, looking at the new output files, it seems like a lot of whitespace has been changed (indentation changes and multiple newlines in various spots). I think it would be best if these sorts of things were to be avoided.

**Comment by ingwinlu** [comment]
the test output should stay clear of whitespace issues as it gets referenced when running tests. If changes somewhere in the codebase affect the test output you get diffs that are already hard to interpret, having random whitespace to diff against does not help.

**Comment by alb-i986** [comment]
I agree about the extra white spaces in the diff, it's not good.
But it looks like they were introduced by previous commits, not by my changes.

For example, thanks to `git bisect` I found that the following whitespaces (and similar pattern)
```
-                By <a class="url fn" href="../author/alexis-metaireau.html">Alexis Métaireau</a>
+                By                         <a class="url fn" href="../author/alexis-metaireau.html">Alexis Métaireau</a>
```
were introduced by 2c25e488c4bc1bd72c592354967497b93ce57e49, as you can see by executing the following lines:
```
git co 2c25e488c4bc1bd72c592354967497b93ce57e49
LC_ALL=en_US.utf8 pelican -o pelican/tests/output/custom/     -s samples/pelican.conf.py samples/content
git diff
```

As well, the errs and warns are displayed even if I checkout master

**Comment by iKevinY** [comment]
Ah, I figured the diff operation done by Travis was whitespace-sensitive, but I guess this isn't the case, since builds were passing despite 2c25e488c4bc1bd72c592354967497b93ce57e49 introducing changes without updating the output files.

**Comment by alb-i986** [comment]
I guess it's just that no one needed to re-generate the test output since a while, like 1 year, according to my investigation. But it's long since the test output got "bad".

**Comment by justinmayer** [comment]
Hi Alberto. Would you be willing to rebase on current master, have another look at your proposed changes, and then push a squashed commit to this branch? Looking forward to getting this merged. (^_^)

**Comment by justinmayer** [comment]
Hi Alberto. Thank you for your contribution.

If we were to do this, I think the implementation should instead look something like:
```
{% if article.tags %}
    <meta name="tags" content="{% for tag in article.tags %}{{ tag }}{{ ', ' if not loop.last }}{% endfor %}" />
{% endif %}
```

That said, my impression is that adding keywords and such to HTML metadata in these more modern years of the web is more likely to *hurt* search engine rankings than to improve them, so I think it's better to leave those portions out.

I submitted #2724, which adds the article summary to the HTML "description" metadata tag. Once merged, this pull request will be closed.

**Pull request closed without merging**
