### PR TITLE
Add Typogrify/SmartyPants dashes config parameter

### PR DESCRIPTION
**Pull request by fancsali**
As a result of  the discussion on #2419, I added a few lines of code, to make the behaviour of Typogrify configurable.

Naming of the different "modes" come from the source code of `smartypants.py`: https://github.com/leohemsted/smartypants.py/blob/master/smartypants.py

### CODE REVIEW

**Comment by oulenz** [comment]
Hm, I'd expect the `oldschool` behaviour to be the default (coming from latex).

**Comment by fancsali** [comment]
> Hm, I'd expect the `oldschool` behaviour to be the default (coming from latex).

Well I myself tend to agree; that's essentially the reason I created this wee change.

However, I felt we shall match the hard-coded default of SmartyPants/Typogrify, so to be backwards compatible: If someone upgrades, the behaviour should not change. Also, I felt, specifying `default` or omitting `TYPOGRIFY_DASHES` entirely should result in the same behaviour.

**Comment by oulenz** [comment]
You're right, and this is a useful tweak!

I was wondering whether we should make this more general, and allow users to pass any smartypants options, but I don't really see anything else anyone might want to change, and that would only make the setting less intuitive.

In fact, could we simply turn this setting into a boolean? (I don't really see why anyone would want to use the inverted setting: -- for em-dash and --- for en-dash.)

Plus, could you test this as part of one of the existing reader tests?

**Comment by justinmayer** [comment]
The `oldschool` setting is a bit of a misnomer. In fact, I think the existing default behavior is for even-more-old-school folks like me who remember using double-hyphens as replacements for em-dashes on typewriters, which had no built-in way to type em-dashes. So the default behavior is very familiar and natural for me. I rarely use en-dashes, and when I do, I type them directly (_option-hyphen_ on macOS).

While I don't understand why folks would want the inverted setting, I'm not sure that's a compelling argument to remove it as an option. Plus, perhaps it makes the most sense to mirror the underlying modes in `smartypants.py` as @fancsali has done here.

In the end, this is going to be a set-it-and-forget-it option for folks, so I'm not overly concerned about it being intuitive. Even a Boolean setting would require explanation as to what it actually does.

**Comment by fancsali** [comment]
I've been contemplating the generic version, but then I too concluded, that it's less intuitive and user friendly to have to muck about with values like `set1`.

Regarding the boolean version, I did think about that too, however, as @justinmayer said, I guess, it's the smart thing to mirror the behaviour of the underlying code. Also, a very good point regarding the `oldschool` method: I still tend to find it intuitive to use double dashes as em-dashes.

All in all, I felt, both the `oldschool` and `oldschool_inverted` have their own legitimate arguments for: If you want to go with the logic "the longer the dash the more hyphens I type", you use one; but it is a complete valid thinking if you'd like to use double-hyphens for em-dashes, and whenever, once in a blue moon, you need en-dashes for things like number ranges, you just go with the triple solution.

@oulenz: Regarding the tests, which readers do you mean: the config-reader, or the ones that read the actual `.rst` and `.md` content?

**Comment by avaris** [comment]
About tests, a single content file generated with different dash options and comparing the expected output should suffice (similar to [this](https://github.com/getpelican/pelican/blob/master/pelican/tests/test_readers.py#L356)).

**Comment by justinmayer** [comment]
@fancsali: Many thanks for resuming work on this in order to add tests. It looks like the `test_article_order_by` and `test_generate_context` tests are currently failing, as well as one or more `flake8` linting checks.

**Comment by fancsali** [comment]
@justinmayer: Cheers for pointing that out. I was finalising that stuff on-the-go, on my Chromebook, and that environment is rather limited, so some tests are expected to fail. Must have missed those in the noise.

**Comment by justinmayer** [comment]
Kudos to @fancsali for this useful addition to the project, and thanks to @oulenz and @avaris for reviewing. It's a pleasure to merge contributions like this. 💫

**Comment by fancsali** [comment]
> Kudos to @fancsali for this useful addition to the project, and thanks to @oulenz and @avaris for reviewing. It's a pleasure to merge contributions like this. 💫

The pleasure is all mine. 😊

**Pull request merged**
