### PR TITLE
WIP: wp_import: resolve links to posts of the form ?attachment_id={post_id}

### PR DESCRIPTION
**Pull request by stuaxo**
Links within wordpress can take the form of ```?attachment_id={post_id}``` linking to another post.

Resolve these links if they point to existing ~~posts~~ attachments.

This works for the one link I have in my own wordpress dump ~~, possibly this should be amalgamated with the existing attachment handling somehow.~~

The link I have is to attachment potentially they could potentially be to anything (my link was created 10 years ago, so not sure what I did in the blog, but maybe I created a link to an unpublished/unsaved post/attachment?)

### CODE REVIEW

**Comment by stuaxo** [comment]
- [x] Gate behind setting
  added ```--wp-resolve```
- [ ] Update unit tests
- [x] Update style to fit in with the rest of the importer
  get_attachments has been updated to search for these links.

**Comment by justinmayer** [comment]
Hi Stuart. Many thanks for your pull request. Could you take a look at the [two failing tests](https://travis-ci.org/github/getpelican/pelican/jobs/463646973) and make the necessary changes so that the test suite passes? Looking forward to merging your contribution! 🏅

**Comment by stuaxo** [comment]
Hi,
   I'll have a go at fixing the tests.   Originally (and more recently) I was holding back from merging this, as although it works, I found get_attachments a little more complex than I'd like after the change.

However, it's probably better I get on and fix the tests so this can get merged and I can get a little further on with my pelican quest :)

S

**Comment by justinmayer** [comment]
That would be great. Thanks, Stuart! 😁

**Comment by stuaxo** [comment]
Hi @justinmayer 
   Closing, everything seems to be working on the current pelican.   So either wasn't a bug or it got fixed in the meantime :)

Will re-open if I manage to reproduce this, as understand a little bit more about how this code works after looking at it :)

Cheers
S

**Pull request closed without merging**
