### PR TITLE
Support inline SVG images

### PR DESCRIPTION
**Pull request by stuaxo**
PR for https://github.com/getpelican/pelican/issues/2561

### CODE REVIEW

**Comment by justinmayer** [comment]
Many thanks for the contribution, Stuart!

@getpelican/reviewers / @bberberov: Any feedback on this implementation?

**Comment by stuaxo** [comment]
I realised I haven't tried the HTML file in a browser separately yet, it's worth verifying that browsers are happy with it.

(I remember trying inline SVG years ago and having trouble if I included the namespace).

**Comment by stuaxo** [comment]
OK, opens in browsers for me, so all good here.

**Comment by justinmayer** [comment]
@stuaxo: Fantastic. Would you be so kind as to add a `RELEASE.md` file as noted in the [Contributing](http://docs.getpelican.com/en/stable/contribute.html#using-git-and-github) section of the docs, and then squash any commits that you think don't need to stand on their own? (if any)

**Comment by justinmayer** [comment]
Many thanks to @stuaxo for the enhancement and to @avaris and @iKevinY for reviewing.

This improvement is included in the just-released [Pelican 4.2](https://github.com/getpelican/pelican/releases/tag/4.2.0). ✨

**Pull request merged**
