### PR TITLE
backslash(\) in pagination urls

### PR DESCRIPTION
**Pull request by ranqiangjun**
eg: 
http://sample.com/category\abc2.html
http://sample.com/category\abc3.html

### CODE REVIEW

**Comment by trwired** [comment]
I just stumbled over this bug on Windows. However, shouldn't the problem be addressed by fixing the Page object rather than replacing backslashes in the template? Putting it there treats the symptoms, not the cause, and every theme that doesn't base upon the simple theme will need to reimplement that fix.

**Comment by avaris** [comment]
@trwired I believe this was fixed by #1581. Did you test it with current master?

**Comment by trwired** [comment]
I just did and after some testing it appears that the problem indeed went away. Thanks!

**Comment by justinmayer** [comment]
@ranqiangjun: Please test with current master and comment here if the problem persists. Thanks!

**Comment by ranqiangjundrupal** [comment]
I reported this bug last year, and it was fixed 18 Feb this year by https://github.com/getpelican/pelican/pull/1581.  @justinmayer

**Comment by ranqiangjun** [comment]
I reported this bug last year, and it was fixed this year by #1581 as @avaris  mentioned. @justinmayer @trwired.

**Pull request closed without merging**
