### PR TITLE
Linted: apply *isort* and *black*

### PR DESCRIPTION
**Pull request by MinchinWeb**
Working on #2897, I discovered that the codebase didn't conform to either *isort* (import sorting) or *black* (general code formating). This resolves both.

As a possible expasion of this, *black* and *isort* may be desirable to be added to the pre-commit setup and/or the lint CI testing.

- [x] Ensured **tests pass** and (if applicable) updated functional test output
- [x] Conformed to **code style guidelines** by running appropriate linting tools
- [ n/a ] Added **tests** for changed code
- [ n/a ] Updated **documentation** for changed code

### CODE REVIEW

**Comment by MinchinWeb** [comment]
This may cover much of the same ground as #2889

**Comment by avaris** [comment]
Lint checker is not [happy](https://github.com/getpelican/pelican/pull/2898/checks?check_run_id=2959515078)

**Comment by justinmayer** [comment]
FYI... The reason that these code formatting tools haven't been used on the Pelican codebase up until this point is that there are existing pull requests in the queue, and I didn't want to cause merge conflicts with those PRs until they can be reviewed and cleared out of the queue. 😊

**Comment by MinchinWeb** [comment]
The linter isn't happy because flake8 doesn't like the import order we're using with isort here. Drop flake8? Configure it to like the isort style I'm using here?

**Comment by ingwinlu** [comment]
let me know if you need a flake8 config that plays nice with isort. i have one lying around.

**Comment by justinmayer** [comment]
This has since been obviated by #3231. But many thanks nonetheless for the PR, @MinchinWeb.

**Comment by MinchinWeb** [comment]
Happy to help! I've been watching Ruff for a while, so I'm interested to see how it's adoption plays out here...

**Pull request closed without merging**
