### PR TITLE
Format all

### PR DESCRIPTION
**Pull request by offbyone**
Resolves: #3216 

# Pull Request Checklist

- [X] Ensured **tests pass** and (if applicable) updated functional test output
- [X] Conformed to **code style guidelines** by running appropriate linting tools

Once this PR is _mostly_ approved, I will add a `.git-blame-ignore-revs` file with the revision of the bulk format commit.

After this, pre-commit should pass. This would supersede #3217 since that's included in here as well.

### CODE REVIEW

**Comment by offbyone** [comment]
I pulled down the docs that were generated and they look fine; I was most worried about those, because docs generation often goes sideways after updates.

**Comment by boxydog** [comment]
If this is ruff-format, there are at least two issues here: 1) ruff-format says it is unstable, I would advise against relying on an unstable tool, 2) now every PR still outstanding will have difficult conflicts to resolve.

I wouldn't do this.

**Comment by boxydog** [comment]
Also: this does not quite supercede #3217, which also includes running `pre-commit run --all` in the github main.yaml.

**Comment by offbyone** [comment]
The third commit in this PR is the outcome of running `pre-commit run --all` 

As for ruff's stability, I'll include https://astral.sh/blog/the-ruff-formatter#production-ready; from my experience with it, I agree with their claim that it is solid enough to use for production codebases.

**Comment by boxydog** [comment]
Sounds like you understand the implications. Works for me.

**Comment by boxydog** [comment]
Ah, but it still doesn't have the github check for pre-commit --all. It looks like this:

```
      # see https://github.com/pre-commit/action/#using-this-action
      - name: pre-commit checks
        uses: pre-commit/action@v2.0.0
        env:
          # it's okay for github to commit to main/master
          SKIP: no-commit-to-branch
```

**Comment by boxydog** [comment]
That would make github check that pre-commit fully passes. That's what's in #3217, but not here yet.

**Comment by offbyone** [comment]
oh, I missed that. Good call out. Would you like me to add that to this pool request, or do you think you'd like to merge 3217 independently?

**Comment by boxydog** [comment]
i would recommend adding the fully-pass check in the same PR as fixing it (with the reformatting), so it doesn't get broken again. whether that happens here, or in 3217, or somewhere else, no opinion.

I just think the pre-commit fixes and the github check that pre-commit passes should be in the same PR to shut the door for good.

**Comment by boxydog** [comment]
justin added `uses: pre-commit/action@v3.0.0`, looks good for me.

Looks like it has to be run through pre-commit once more, tho.

**Comment by justinmayer** [comment]
@offbyone: For reasons that are boring, I needed to do some surgery on this PR, and since I can't re-write history in your fork, I created a new PR that contains these commits in a cleaned-up form: #3231

**Pull request closed without merging**
