### PR TITLE
Convert FEED settings from `%s` to `{slug}` redux

### LINKED ISSUE #2106: `TAG_FEED_ATOM = 'label.{slug}.atom.xml'` breaks Pelican
When defining *_URL and *_SAVE_AS settings, `{slug}` replacements are valid. That is to say the following are valid:

```
TAG_URL = 'label/{slug}/'
TAG_SAVE_AS = 'label/{slug}/index.html'
```

However, if the same form is tried on RSS/Atom feed name settings, Pelican breaks with a critial error. That is to say, the following (which would follow from the above) is NOT valid:

```
TAG_FEED_ATOM = 'label.{slug}.atom.xml'
```

Instead, `%s` substitution must be used. That is to say, the following is valid:

```
TAG_FEED_ATOM = 'label.%s.atom.xml'
```

This seems to be the case for all RSS/Atom feed name settings.

Is it possible to get feed name settings to support `{}` substitution, to match *_URL and *_SAVE_AS settings?

### PR DESCRIPTION
**Pull request by MinchinWeb**
Closes #2106, Closes #2383.

Rework of #2383 to try and isolate FEED setting changes. See #2383 for development discussion.

### CODE REVIEW

**Comment by justinmayer** [comment]
Many thanks to @MinchinWeb for the enhancement and to @avaris for the review! 🚀

**Comment by jorgesumle** [comment]
I think that this change is preventing me to update to Pelican 4.0.1. I get `feeds/{slug}.atom.xml` in the feed URL generated with `{{ FEED_DOMAIN }}/{{ CATEGORY_FEED_ATOM|format(slug=category.slug) }}` (as recommended in the [release note of Pelican 4.0](https://blog.getpelican.com/pelican-4.0-released.html)). This is my setting from publishconf.py: `CATEGORY_FEED_ATOM = 'feeds/{slug}.atom.xml'`. Have I wrongly configured it or is it a bug?

**Comment by mosra** [comment]
I think it should be `.format(slug=category.slug)`, not `|format(slug=category.slug)` (dot instead of a pipe).

**Comment by jorgesumle** [comment]
Yes, the changelog and the blog post are wrong. I [updated the changelog](https://github.com/getpelican/pelican/pull/2507). Someone should update the blog post, I cannot submit a pull request, because the article of the latest post is not committed to the official repository.

**Comment by justinmayer** [comment]
Thank you for identifying the problem, @mosra. And thank you, Jorge, for fixing the changelog.

I fixed the blog post. I also (belatedly) pushed the article source to the repository via 
https://github.com/getpelican/pelican-blog/commit/8978dd28f3299d3dd63c9d99c9dffc1aa953c4aa.

**Pull request merged**
