### PR TITLE
Jinja template, css, js precommit filters

### PR DESCRIPTION
**Pull request by boxydog**
# Pull Request Checklist

- [x] Ensured **tests pass** and (if applicable) updated functional test output
- [x] Conformed to **code style guidelines** by running appropriate linting tools

This is an automated replacement for #2379.

There are no manual fixes.

If this is acceptable, we can merge it and close #2379.

If this change gets conflicted, we can remake the PR, drop in the .pre-commit-config.yaml changes, and apply the rest automatically. (To apply to pelican/tests/output, temporarily comment out that line in the config, run `pre-commit run --all djhtml` and djcss and djjs, then uncomment that line.)

### CODE REVIEW

**Comment by boxydog** [comment]
I'm wrong. #2379 changes 124 files, and this only changes 39, so this must be doing less?

**Comment by boxydog** [comment]
Ah, pelican/tests/output was excluded. I ran the same pre-commit filters (djhtml, djcss, djjs) on that directory as well, and now this change is 160 files (compared to 124 in #2379).

**Comment by boxydog** [comment]
One subtlety: pelican/tests/output is still excluded from the pre-commit filter, so for that directory this is a one-time change. Perhaps we should change pre-commit to include those dirs?

**Comment by boxydog** [comment]
FYI, I looked at four jinja template formatting projects:

* curlylint, mentioned in #2379. Last commit two years ago.
* jinjalint. Last commit six years ago.
* djLint. Last commit four months ago.
* djhtml. Last commit three weeks ago.

It looked to me like djhtml was clean, active, maintained. djLint might also be a reasonable choice (not sure), but I went with djhtml.

**Comment by justinmayer** [comment]
I imagine you're right that `pre-commit` should apply the same HTML/CS/JSS formatting rules to `pelican/tests/output`.

Regarding template formatting project selection, I don't have a strong opinion on the matter. I think the key difference is that [DjHTML](https://github.com/rtts/djhtml) only focuses on _indentation_, while, say, [djLint](https://github.com/djlint/djlint) includes formatting in its scope, with for example [configuration options](https://djlint.com/docs/configuration/) for inserting newlines before/after tags, closing void tags, etc. Like [DjHTML](https://github.com/rtts/djhtml), it seems [djLint](https://github.com/djlint/djlint) also has configuration options for formatting CSS & JS, for what that's worth.

That all said, I think the fact that [DjHTML](https://github.com/rtts/djhtml) only focuses on indentation is perhaps a feature rather than a shortcoming, and it's probably the one I would be inclined to select as well.

**Comment by boxydog** [comment]
What are next steps here?

I filed PR #3316 to apply pre-commit filters to all directories. Could merge that, then redo this, then merge this?

**Comment by boxydog** [comment]
Sounds good, I'll unconflict this right now.

**Comment by boxydog** [comment]
To unconflict, I did

* `git reset HEAD~2` (to roll back to just .pre-commit-config.yaml changes)
* `git pull --rebase origin main` (and resolved conflicts), to set up .pre-commit-config.yaml properly and get the whitespace changes from master
* `pre-commit run --all` to re-apply changes to templates, css, js

So, no manual fixes.

**Review by justinmayer — APPROVED** [review]
Thanks, @boxydog!

**Pull request merged**
