### PR TITLE
Separate pip requirements. Fixes #1808

### LINKED ISSUE #1808: Separate Pip requirements files for each use case
**Problem:** The current `dev_requirements.txt` file was originally meant for use by Pelican developers but is now also used by Travis and `tox` for testing purposes. These are two different use cases that are not well served by a single Pip requirements file.

**Solution:** Create separate requirements files for each use case while minimizing redundancy and staying DRY.

I’d like to propose the following revised structure for Pip requirements:

    project_root/
    └── requirements/
        ├── developer.pip
        └── test.pip

Proposed contents for `requirements/test.pip`:

    # Tests
    mock

    # Optional packages
    Markdown
    BeautifulSoup4
    lxml
    typogrify

Proposed contents for `requirements/developer.pip`:

    -r test.pip

    # Development
    flake8
    -e git+https://github.com/public/flake8-import-order#egg=flake8-import-order
    sphinx
    tox

    # Release issuance
    bumpr==0.2.0
    wheel

As an additional bonus, using the `.pip` extension instead of the generic and information-free `.txt` suffix will allow for easy syntax highlighting (e.g., in Vim).

### PR DESCRIPTION
**Pull request by atodorov**
I have followed the discussion in #1808 and just provided the implementation. Let me know if something needs to be updated. CC @justinmayer, @avaris, @ingwinlu, @kylef, @iKevinY

Regards,
@MrSenko

### CODE REVIEW

**Comment by justinmayer** [comment]
Many thanks for the implementation, Alexander.  (^_^)

This looks good to me. Anyone else have any comments?

**Comment by ingwinlu** [comment]
missed edits in https://github.com/getpelican/pelican/blob/master/docs/contribute.rst

**Comment by justinmayer** [comment]
@ingwinlu: Thanks for pointing that out. I'll rectify that shortly.

**Comment by ingwinlu** [comment]
nvm it was already done by @atodorov in the pr

**Pull request merged**
