### PR TITLE
Support for python -m pelican

### PR DESCRIPTION
**Pull request by timgates42**
Addresses #2523

### CODE REVIEW

**Comment by avaris** [comment]
TBH, I don't like the `quickstart` bit. If needed, you can already do:

```
python -m pelican.tools.pelican_quickstart
```

Adding dummy packages just to shorten the command slightly seems unnecessary.

**Comment by timgates42** [comment]
Cool, I'm happy to drop the quickstart - will do

**Comment by timgates42** [comment]
Thanks @avaris - updated now

**Comment by avaris** [comment]
Can you [squash](https://github.com/getpelican/pelican/wiki/Git-Tips#squashing-commits) the commits? Otherwise, looks good.

**Comment by timgates42** [comment]
Sure, will do

**Comment by timgates42** [comment]
Thanks @avaris - updated now

**Comment by timgates42** [comment]
So what's next for this PR, I checked the CONTRIBUTING guidelines and I notice it mentions to please use the GitHub `hub` tool when opening PRs which I did not do, I worry that I didn't follow the right process so it won't get picked up for a second review or the next step.

**Comment by justinmayer** [comment]
Many thanks for reviewing, @avaris. 🏅 

@timgates42: Using `hub` to convert an existing issue to a pull request is handy, which is why it's mentioned in the Contributing docs, but doing so is by no means strictly necessary. Everything here looks good to me. Thank you for your first contribution to Pelican! 🎉

**Pull request merged**
