### PR TITLE
pelican_import: Fix post titles that are entirely made of spaces

### PR DESCRIPTION
**Pull request by stuaxo**
get_filename: 
   fixup names that are entirely made up of spaces.
   use "post_name", where the parameter is the postname.

### CODE REVIEW

**Comment by stuaxo** [comment]
Seeing if there's anything useful in my old import branch.

**Comment by stuaxo** [comment]
When I import, this fixes the issue of ending up with a lot of pages named ```-```

**Comment by oulenz** [comment]
Seems reasonable to me. :+1:

**Comment by justinmayer** [comment]
Many thanks to @stuaxo for the fix and to @oulenz and @avaris for reviewing.

**Comment by stuaxo** [comment]
Thanks :)

**Pull request merged**
