### PR TITLE
Initialize locale for Python 2+ in quickstart script. Fixes #2043

### LINKED ISSUE #2043: Quickstart locale error: 'NoneType' object has no attribute 'split'
Pelican version: 594b9c96 (installed with `pip install -e "git+https://github.com/getpelican/pelican.git#egg=pelican"`)
Python: 2.7.12 Windows x64 (within a virtual environment)
Using:
> blinker (1.4)
docutils (0.12)
feedgenerator (1.9)
Jinja2 (2.8)
Markdown (2.6.7)
MarkupSafe (0.23)
pelican (3.6.4.dev0, d:\documents\pelican\src\pelican)
pip (8.1.2)
Pygments (2.1.3)
python-dateutil (2.5.3)
pytz (2016.7)
setuptools (28.7.1)
six (1.10.0)
smartypants (1.8.6)
typogrify (2.0.7)
Unidecode (0.4.19)
wheel (0.30.0a0)

When invoking `pelican-quickstart`, I am getting the following stacktrace:

>(Pelican) D:\Documents\Pelican>pelican-quickstart
Traceback (most recent call last):
  File "D:\Documents\Pelican\Scripts\pelican-quickstart-script.py", line 11, in <module>
    load_entry_point('pelican', 'console_scripts', 'pelican-quickstart')()
  File "d:\documents\pelican\lib\site-packages\pkg_resources\__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "d:\documents\pelican\lib\site-packages\pkg_resources\__init__.py", line 2608, in load_entry_point
    return ep.load()
  File "d:\documents\pelican\lib\site-packages\pkg_resources\__init__.py", line 2268, in load
    return self.resolve()
  File "d:\documents\pelican\lib\site-packages\pkg_resources\__init__.py", line 2274, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "d:\documents\pelican\src\pelican\pelican\tools\pelican_quickstart.py", line 52, in <module>
    'lang': locale.getlocale()[0].split('_')[0],
AttributeError: 'NoneType' object has no attribute 'split'

### PR DESCRIPTION
**Pull request by amyspark**
Previously #2054 . I apologise for recreating the pull request, but I messed up the commits' author metadata.
Includes a check for python 2 only, as requested.

### CODE REVIEW

**Comment by leotrs** [comment]
Looks to me ready for merge. @justinmayer ?

**Comment by justinmayer** [comment]
Does our resident locale/encoding expert @avaris have any thoughts on this?

**Comment by avaris** [comment]
Locale-wise good, but can we not add superfluous newlines around the `import`? :)

**Comment by amyspark** [comment]
@avaris, I've removed them as per your request. Please check that everything's in order.

**Comment by justinmayer** [comment]
@amyspark: Would you please [squash](https://github.com/getpelican/pelican/wiki/Git-Tips#squashing-commits) the fix-up commit into the original commit? That will help keep the commit history tidy.

**Comment by amyspark** [comment]
@justinmayer, I've tried to do it but it just returns `noop`.

**Comment by justinmayer** [comment]
Thanks to @amyspark for the enhancement and to all the folks who reviewed.  (^_^)

**Pull request merged**
