### PR TITLE
Use unichr() instead of chr() with Python 2.

### PR DESCRIPTION
**Pull request by andreacorbellini**
This fixes the problem noticed by @justinmayer on https://github.com/getpelican/pelican/pull/1802#issuecomment-142351070

### CODE REVIEW

**Comment by andreacorbellini** [comment]
I forgot to add a test for named entities outside the ASCII range

**Comment by andreacorbellini** [comment]
Done!

**Comment by justinmayer** [comment]
Thanks, Andrea!

**Comment by ingwinlu** [comment]
even added tests to cover the issue in future. Quality stuff here.

**Comment by justinmayer** [comment]
As Winlu said... Bravo!

**Pull request merged**
