### PR TITLE
Add pandoc2 support to pelican-import. Fix #2255

### LINKED ISSUE #2255: pelican-import corrupts posts imported from WordPress
Hello,

I tried to move my blog ( https://eax.me/ ) from WordPress to Pelican using pelican-import. It works for the most part. There were a few difficulties but I managed to find workarounds for most of them. Particularly pelican-import doesn't handle images well and doesn't support CodeColorer plugin so I had to use some regular expressions (see below).

Also I discovered that pelican-import doesn't work with pandoc 2.0.2 properly so I had to patch the script around line 729:

```
            parse_raw = ''
            cmd = ('pandoc {0} --from=html'
                   ' --to={1}+raw_html -o "{2}" "{3}"')
            cmd = cmd.format(parse_raw, out_markup,
                             out_filename, html_filename)
```

These are minor issues though. The most serious issues are the following.

1. After migration characters like `'`, `"` and `$` were replaced to `\'`, `\"` and `\$`. I can't just replace these sequences back to `'`, `"` and `$` since these sequences sometimes are used in code snippets. There is a similar issue with the dash symbol that after migrations turn from `---` to `\-\--`.

2. Also in some code snippets code like `#include <something.h>` just turns into `#include`.

3. Last but not least one of the posts created by pelican-import (see below) hangs `make devserver` with 100% CPU usage.

You can reproduce all these issues using the XML file that I exported from WordPress. Please leave your email and I will send it to you.

Exact steps to reproduce:

```
perl -pi -e 's/\[cci.*?\]/<code>/g' ~/temp/del-me/wordpress.2017-11-29.xml
perl -pi -e 's/\[\/cci.*?\]/<\/code>/g' ~/temp/del-me/wordpress.2017-11-29.xml
perl -pi -e 's/\[cc_(\w+).*?\]/<pre><code>:::$1/g' ~/temp/del-me/wordpress.2017-11-29.xml
perl -pi -e 's/\[cc.*?lang="(\w+)".*?\]/<pre><code>:::$1/g' ~/temp/del-me/wordpress.2017-11-29.xml
perl -pi -e 's/\[cc.*?\]/<pre><code>/g' ~/temp/del-me/wordpress.2017-11-29.xml
perl -pi -e 's/\[\/cc.*?\]/<\/code><\/pre>/g' ~/temp/del-me/wordpress.2017-11-29.xml
perl -pi -e 's/<img .*?((src=".*?" alt=".*?")|(alt=".*?" src=".*?)).*?>/<img $1 \/>/g' ~/temp/del-me/wordpress.2017-11-29.xml
perl -pi -e 's/<span style="white\-space: nowrap;">(.*?)<\/span>/$1/g' ~/temp/del-me/wordpress.2017-11-29.xml
perl -pi -e 's!"https?:\/\/eax\.me\/([a-z0-9\-_]+)\/"!"https:\/\/eax.me\/$1.html"!g' ~/temp/del-me/wordpress.2017-11-29.xml
pelican-import -o content/ -m markdown --wpfile ~/temp/del-me/wordpress.2017-11-29.xml
```
Run `make devserver` to make sure that content/mojolicious.md hangs the server (issue 3). Temporary replace it somewhere and run `make devserver` again.

Then see:

```
http://localhost:8000/diy-presentation-remote.html
http://localhost:8000/elliptic-curves-crypto.html
```
^ symbols `$`, `'` and `"` turned into `\$`, `\'` and `\"` (issue 1).

```
http://localhost:8000/cpp-gtest.html
```
^ `#include <something.h>` was replaced to `#include` (issue 2).

Pelican version is 3.7.1.

### PR DESCRIPTION
**Pull request by davidag**
Tests are not passing. I am working on it.

### CODE REVIEW

**Comment by davidag** [comment]
Tests passing.

It could be recommendable to also run tests with pandoc2 installed. [There is a binary without dependencies available.](https://pandoc.org/installing.html#linux) I'm not sure, but travis-ci seems the place to do it.

@justinmayer: what do you think?

**Comment by justinmayer** [comment]
@davidag: Running tests with Pandoc2 installed seems sensible enough to me. Would you like to add a commit to this pull request that modifies Pelican's Travis configuration to ensure Pandoc2 is installed?

**Comment by davidag** [comment]
@justinmayer: I've made the following changes to make tests run with pandoc1 and pandoc2:

* Add 4 new environments to Travis, one for each supported python version, using pandoc2 instead of pandoc1 (installed by default on Ubuntu 14.04 -the distro used in Travis-).
* pandoc2 is only downloaded and installed by tox when the environment includes the factor "pandoc2". Non-pandoc2 build speed should not be affected by these changes.
* Use the precompiled binary without dependencies in order to support any Linux distro. I understand we want developers to be able to run the tests locally, without using Travis.

**Comment by justinmayer** [comment]
@phillipao: Can you provide @davidag with an example file(s) or some other detailed information regarding how he might reproduce the problem?

**Comment by justinmayer** [comment]
@davidag: As a heads-up, I may include your Pandoc fix in Pelican 3.8 but defer the Travis-related portions. There's a strong possibility that an upcoming release will move the importer out of core into a separate module/repository, at which point the Travis-related portions of this PR would be a better fit for the latter rather than core.

**Comment by phillipao** [comment]
Sure. 
[philoblog.zip](https://github.com/getpelican/pelican/files/2241965/philoblog.zip). This contains one xml file, exported from my wordpress blog. Imported like this:

```shell
pelican-import --wpfile -o ~/pelican-output ~/Downloads/philo039sbigbadgeekeryblog.wordpress.2018-07-27.xml --markup markdown
```

With pandoc2, and without this pr, of course, the command fails. With the pr patched in, it succeeds but inserts the escape characters as I described.

**Comment by davidag** [comment]
@phillipao, thanks for the report and the file! I've already fixed the escaped character's problem.

@justinmayer: Moving the importers to a new repo seems like a great idea to me. I think that at least the WordPress importer could be improved in several ways. If I can help with the migration, just let me now.

**Comment by justinmayer** [comment]
@davidag: Many thanks for the offer, which I will gladly take you up on when the time comes. Much appreciated! 😁 

Given that, would you be so kind as to do the following for me?

1. Move the Pandoc2 install script, .tox, and .travis.yml changes to a separate pull request.
2. Rebase and squash the remaining changes into discrete, logical commits. (It can be one commit, five, whatever number/separation you think makes sense from a change-set evolution history perspective.)

My apologies for asking for these last two steps. I know you've put considerable effort into this endeavor, and I certainly want to respect your time. Please know that this will help me a great deal. Many thanks in advance!

**Comment by justinmayer** [comment]
Many thanks for your efforts and responsiveness, David. Much appreciated! 🎉

**Pull request merged**
