### PR TITLE
Use Furo as Sphinx documentation theme (redux)

### PR DESCRIPTION
**Pull request by justinmayer**
Follow-up endeavor that builds on top of #2966.

### CODE REVIEW

**Review by pauloxnet — APPROVED** [review]

**Comment by pauloxnet** [comment]
@justinmayer LGTM

**Comment by lcfd** [comment]
Amazing!

**Comment by justinmayer** [comment]
Have I mentioned that I am often frustrated by ReadTheDocs? 😖 

https://readthedocs.org/projects/pelican/builds/17593006/

**Comment by justinmayer** [comment]
This bizarre error only happens during the ePub build, so for now I have disabled ePub builds in ReadTheDocs Admin > Advanced Settings.

**Comment by pauloxnet** [comment]
Great! The Pelican's documentation looks better now:
https://docs.getpelican.com/en/latest/

**Pull request merged**
