### PR TITLE
Upgrade code base for Python 3.8 and above

### PR DESCRIPTION
**Pull request by justinmayer**
This upgrades the Pelican code base for Python 3.8 and above. Performed via:

	pipx run pyupgrade --py38-plus pelican/**/*.py

### CODE REVIEW

**Review by pauloxnet — APPROVED** [review]
LGTM

**Comment by justinmayer** [comment]
Follow-up question… Is this the kind of commit that should be added to [`.git-blame-ignore-revs`](https://github.com/getpelican/pelican/blob/master/.git-blame-ignore-revs)? Or is there some reason to have these changes show up in `git blame`?

**Comment by pauloxnet** [comment]
> Follow-up question… Is this the kind of commit that should be added to [`.git-blame-ignore-revs`](https://github.com/getpelican/pelican/blob/master/.git-blame-ignore-revs)? Or is there some reason to have these changes show up in `git blame`?

In other similar projects (e.g. Django) is common to ignore this type of commit.

**Review by avaris — APPROVED** [review]
Looks good. I am fine with excluding this from blame.

**Review by pauloxnet — APPROVED** [review]

**Comment by justinmayer** [comment]
@pauloxnet & @avaris: Thanks for having a look!

**Pull request merged**
