### PR TITLE
No tests in bdist

### LINKED ISSUE #1409: installing 3.4.0 with python3 fails on linux depending on locale
## Summary

Trying to install pelican 3.4.0 with python 3 on a linux box fails if the locale is not UTF-8. This seems to be caused by the pathname of some files containing non-ascii characters (e.g. décembre, février).

### Setup a virtualenv with python3
```
virtualenv -p python3 virtualenv_python3
cd virtualenv_python3
source bin/activate
```
### Set a non utf-8 locale
```
export LANG=C
```
or
```
export LANG=fr_FR
```
### Try to install pelican with pip
```
pip install pelican
```

## Results

It fails with the following traceback:
```
  File "<string>", line 1, in <module>
  File "/home/user/virtualenv_python3/build/pelican/setup.py", line 48, in <module>
    test_suite='pelican.tests',
  File "/usr/lib64/python3.3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.3/distutils/dist.py", line 930, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.3/distutils/dist.py", line 949, in run_command
    cmd_obj.run()
  File "/home/user/virtualenv_python3/lib/python3.3/site-packages/setuptools/command/install.py", line 53, in run
    return _install.run(self)
  File "/usr/lib64/python3.3/distutils/command/install.py", line 574, in run
    self.run_command('build')
  File "/usr/lib64/python3.3/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.3/distutils/dist.py", line 949, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.3/distutils/command/build.py", line 126, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.3/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.3/distutils/dist.py", line 949, in run_command
    cmd_obj.run()
  File "/home/user/virtualenv_python3/lib/python3.3/site-packages/setuptools/command/build_py.py", line 90, in run
    self.build_package_data()
  File "/home/user/virtualenv_python3/lib/python3.3/site-packages/setuptools/command/build_py.py", line 148, in build_package_data
    self.mkpath(os.path.dirname(target))
  File "/usr/lib64/python3.3/distutils/cmd.py", line 339, in mkpath
    dir_util.mkpath(name, mode, dry_run=self.dry_run)
  File "/usr/lib64/python3.3/distutils/dir_util.py", line 42, in mkpath
    if os.path.isdir(name) or name == '':
  File "/home/user/virtualenv_python3/lib64/python3.3/genericpath.py", line 41, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0301' in position 58: ordinal not in range(128)
```

The complete pip.log is [here](https://gist.github.com/benoit-monin/52818f2fe39b718753d2).

### LINKED ISSUE #1545: Installing Pelican on Python 3 and Windows yields UnicodeDecodeError
Hi,

When installating pip on windows 7 with python 3.4, I get the following error (same error as https://github.com/getpelican/pelican/issues/1414):

```
Installing collected packages: pelican, python-dateutil, jinja2, docutils, blinker, feedgenerator, unidecode, pytz, six, pygments, markupsafe
Cleaning up...
Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Python34\lib\site-packages\pip\req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\Python34\lib\site-packages\pip\req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "C:\Python34\lib\site-packages\pip\req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "C:\Python34\lib\site-packages\pip\wheel.py", line 359, in move_wheel_files
    for row in reader:
  File "C:\Python34\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7407: character maps to     <undefined>

Storing debug log for failure in C:\Users\admin\pip\pip.log
```

Issue 1414 was closed concluding to an encoding bug with pip. I don't think it is the case. Here are my observations:

I get this error when installing from pip, either locally or from PyPI. Installing from sources does not cause any problem. On windows, the problem already occurs when we build the wheel using setup.py and bdist_wheel. Hence, this is probably not a **pip specific problem**.

I search for all the files containing a 0x81 byte. All those files are located in the tests or themes directories. Consequently, I tried to rebuild the wheel file without the tests directory and the wheel archive builds and installs correctly. There is an encoding problem in one of the test files and I'm still searching for it.

This is a windows specific problem since somewhere during the construction/installation of the wheel, python tries to read a file and supposes it is encoded in cp 1252. However, the 0x81 byte does not mean anything in the 1252 windows encoring. I now have to search for the UTF-8 characters that contain a 0x81 byte in their representation.

Kind regards

Thierry

### LINKED ISSUE #1609: Doesn't install on Python 3.4
Pip fails with decoding errors cause Pelican includes the test suite in the package. And the test suite has weird characters in the tests directories. Eg: https://github.com/getpelican/pelican/tree/master/pelican/tests/output/custom_locale/posts/2012/f%C3%A9vrier

Sample output:
```
ERROR: invocation failed (exit code 2), logfile: C:\Users\ionel_000\Projects\blog.ionelmc.ro\.tox\gen\log\gen-1.log
ERROR: actionid=gen
msg=getenv
cmdargs=[local('C:\\Users\\ionel_000\\Projects\\blog.ionelmc.ro\\.tox\\gen\\Scripts\\pip.EXE'), 'install', '--pre', 'pelican==3.5.0']
env={'TMP': 'C:\\Users\\IONEL_~1\\AppData\\Local\\Temp', 'COMPUTERNAME': 'JME-PC', 'VS110COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools\\', 'USERDOMAIN': 'JME-PC', 'VS100COMNTOOLS': 'C
:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\Tools\\', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'COMMANDER_PATH': 'C:\\Totalcmd', 'COMMONPROGRAMFILES': 'C:\\Program F
iles\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel', 'PROGRAMFILES': 'C:\\Program Files', 'PROCESSOR_REVISION': '2a07', 'SYSTEMROOT': 'C:\\Windows', 'PATH': 'C:\\Users\\ionel
_000\\Projects\\blog.ionelmc.ro\\.tox\\gen\\Scripts;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;c:\\Programs\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System3
2\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;c:\\Python27\\Scripts\\;C:\\Program Files\\TortoiseSVN\\bin;c:\\Python27\\;C:\\Program Files\\nodejs;C:\\Program Files\\TortoiseHg\\;C:\\Program Files\\Google\\Clo
ud SDK\\google-cloud-sdk\\bin;C:\\Program Files (x86)\\Git\\cmd;C:\\Program Files\\Microsoft Windows Performance Toolkit\\;C:\\Users\\ionel_000\\AppData\\Roaming\\Python\\Scripts;C:\\Users\\ionel_000\\AppData\\Roaming\\n
pm;C:\\Program Files (x86)\\Google\\google_appengine\\;c:\\PyPy\\', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'LANG': 'en_US', 'VIRTUAL_ENV': 'C:\\Users\\ionel_000\\Projects\\blog.ionelmc.ro\\.tox\\gen', 'TEMP': 'C
:\\Users\\IONEL_~1\\AppData\\Local\\Temp', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'PYTHONHASHSEED': '848', 'LOCALAPPDA
TA': 'C:\\Users\\ionel_000\\AppData\\Local', 'HOMEPATH': '\\Users\\ionel_000', 'USERDOMAIN_ROAMINGPROFILE': 'JME-PC', 'VS120COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\Tools\\', 'PROGRAMW
6432': 'C:\\Program Files', 'USERNAME': 'ionel_000', 'LOGONSERVER': '\\\\MicrosoftAccount', 'PROMPT': 'C\x08L\x08I\x08N\x08K\x08 \x08$P$G', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'PROGRAMDATA': 'C:\\ProgramData', '
PYTHONPATH': '.', 'COMMANDER_DRIVE': 'C:', 'COMMANDER_EXE': 'C:\\Totalcmd\\TOTALCMD64.EXE', 'SCITE_HOME': 'C:\\ProgramData\\SciTE', 'SESSIONNAME': 'Console', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.
MSC;.PY', 'FP_NO_HOST_CHECK': 'NO', 'WINDIR': 'C:\\Windows', 'OPENSSL_CONF': 'C:\\OpenSSL-Win64\\bin\\openssl.cfg', 'HOMEDRIVE': 'C:', 'APPDATA': 'C:\\Users\\ionel_000\\AppData\\Roaming', 'COMMANDER_INI': 'C:\\Users\\ion
el_000\\wincmd.ini', 'SYSTEMDRIVE': 'C:', 'NUMBER_OF_PROCESSORS': '8', 'PROCESSOR_LEVEL': '6', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'OS': 'Windows_NT', 'PUBLIC': 'C:\\Users\\Public', 'USERPROFILE': 'C
:\\Users\\ionel_000'}
Collecting pelican==3.5.0
Collecting python-dateutil (from pelican==3.5.0)
  Downloading python_dateutil-2.4.0-py2.py3-none-any.whl (175kB)
Collecting docutils (from pelican==3.5.0)
Collecting pytz>=0a (from pelican==3.5.0)
Collecting unidecode (from pelican==3.5.0)
Collecting six>=1.4 (from pelican==3.5.0)
Collecting feedgenerator>=1.6 (from pelican==3.5.0)
Collecting blinker (from pelican==3.5.0)
Collecting jinja2>=2.7 (from pelican==3.5.0)
Collecting pygments (from pelican==3.5.0)
  Downloading Pygments-2.0.2-py3-none-any.whl (672kB)
Collecting markupsafe (from jinja2>=2.7->pelican==3.5.0)
Installing collected packages: markupsafe, pygments, jinja2, blinker, feedgenerator, six, unidecode, pytz, docutils, python-dateutil, pelican











  Exception:
  Traceback (most recent call last):
    File "C:\Users\ionel_000\Projects\blog.ionelmc.ro\.tox\gen\lib\site-packages\pip\basecommand.py", line 232, in main
      status = self.run(options, args)
    File "C:\Users\ionel_000\Projects\blog.ionelmc.ro\.tox\gen\lib\site-packages\pip\commands\install.py", line 347, in run
      root=options.root_path,
    File "C:\Users\ionel_000\Projects\blog.ionelmc.ro\.tox\gen\lib\site-packages\pip\req\req_set.py", line 549, in install
      **kwargs
    File "C:\Users\ionel_000\Projects\blog.ionelmc.ro\.tox\gen\lib\site-packages\pip\req\req_install.py", line 740, in install
      self.move_wheel_files(self.source_dir, root=root)
    File "C:\Users\ionel_000\Projects\blog.ionelmc.ro\.tox\gen\lib\site-packages\pip\req\req_install.py", line 949, in move_wheel_files
      isolated=self.isolated,
    File "C:\Users\ionel_000\Projects\blog.ionelmc.ro\.tox\gen\lib\site-packages\pip\wheel.py", line 390, in move_wheel_files
      for row in reader:
    File "C:\Users\ionel_000\Projects\blog.ionelmc.ro\.tox\gen\lib\encodings\cp1250.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7822: character maps to <undefined>


ERROR: could not install deps [pelican==3.5.0]; v = InvocationError('C:\\Users\\ionel_000\\Projects\\blog.ionelmc.ro\\.tox\\gen\\Scripts\\pip.EXE install --pre pelican==3.5.0 (see C:\\Users\\ionel_000\\Projects\\blog.ion
elmc.ro\\.tox\\gen\\log\\gen-1.log)', 2)
___________________________________ summary ___________________________________
ERROR:   gen: could not install deps [pelican==3.5.0]; v = InvocationError('C:\\Users\\ionel_000\\Projects\\blog.ionelmc.ro\\.tox\\gen\\Scripts\\pip.EXE install --pre pelican==3.5.0 (see C:\\Users\\ionel_000\\Projects\\b
log.ionelmc.ro\\.tox\\gen\\log\\gen-1.log)', 2)
```

### PR DESCRIPTION
**Pull request by ionelmc**
Discussion from IRC:

```
18:38 <ionelmc> can you stop including the tests in the installed package?
18:39 <+justmay> Fine with me. Care to submit a PR that addresses that?
18:39 <ionelmc> sure
18:47 <ionelmc> justmay: is `.mailmap` a stray file?
18:47 <ionelmc> look like your sdist is incomplete
18:48 <ionelmc> doesn't include all the docs and test conf
18:50 <ionelmc> justmay: oh snap. i have to move out the tests to fix this :-)
18:51 <ionelmc> because include_package_data is used any included data file overlaying the package is going into the bdist
18:51 <+justmay> ionelmc: .mailmap is there by design. See "Mapping Authors": https://www.kernel.org/pub/software/scm/git/docs/git-shortlog.html
18:52 <ionelmc> mkay
18:52 <ionelmc> justmay: you're not going to have a problem with the tests dir at the same level as pelican package right?
18:53 → e-Flex joined (~e-Flex@h-62-241.a259.priv.bahnhof.se)
18:54 <+justmay> There's no other way to prevent inclusion of tests in the installed package?
18:55 <ionelmc> justmay: there are two horrible ways
18:55 <ionelmc> don't include it in the sdist (highly undesirable)
18:55 <ionelmc> or
18:55 <ionelmc> manually specify package_data 
18:55 <ionelmc> which i can do it correctly for you know, but it will be error prone to maintain
18:56 <ionelmc> s/know/now/
18:56 <ionelmc> i think that's also not desirable
18:56 <ionelmc> that's why i think moving them out is ok
18:57 <ionelmc> i'll fix the test configuration to work that way
18:57 <ionelmc> justmay: agree? :-)
18:59 <+justmay> ionelmc: Quite honestly, I don't have the bandwidth this morning to dig deeply enough into this topic. Would you submit an issue so we (i.e., the community) can discuss this and come to a consensus?
19:00 <ionelmc> justmay: there's already https://github.com/getpelican/pelican/issues/1409 - i seriously doubt a new issue will help in any way
19:01 <winlu> ionelmc: justs prune tests and be done with it
19:01 <ionelmc> justmay: it's either the relocation or manual package_data, make a choice :-)
19:01 <ionelmc> winlu: pruning the tests will remove them from sdist
```

Closes #1609. Closes #1545. Closes #1409.

### CODE REVIEW

**Comment by justinmayer** [comment]
@ionelmc: With these changes, it would seem that [Travis is not running tests](https://travis-ci.org/getpelican/pelican/builds/49962641).

**Comment by ionelmc** [comment]
Good catch but Coveralls does this automatically for you :wink: 

If you enable it I'll add configuration for it.

**Comment by ionelmc** [comment]
Mkay, there are some merge conflicts ....

**Comment by ionelmc** [comment]
Rebased now. @justinmayer seems coveralls isn't reporting any build status. Can you check? Maybe you just need to reauth with coveralls.

**Comment by ingwinlu** [comment]
the move to a more traditional split of packages is what mainly does it for me, i.e. move tests out of the pelican directory.
If you look at other python projects it would be even more expected to not have pelican_tests but just tests.

the changes to the sdists and bdists also would also help the ongoing effort to make pelican play nice with windows.

**Comment by ionelmc** [comment]
@justinmayer Any updates here? It's not clear what you're waiting for.

**Comment by ionelmc** [comment]
I've been thinking, maybe we should have something like this: https://bitbucket.org/pypa/setuptools/pull-request/133/dont-install-tests-in-site-packages/diff

**Comment by ingwinlu** [comment]
this won't be looked at until it at least confirms with what we require of pull requests: http://pelican.readthedocs.org/en/latest/contribute.html#using-git-and-github

**Comment by ionelmc** [comment]
It's not clear what you're asking of.

On Thursday, May 28, 2015, winlu <notifications@github.com> wrote:

> this won't be looked at until it at least confirms with what we require of
> pull requests:
> http://pelican.readthedocs.org/en/latest/contribute.html#using-git-and-github
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getpelican/pelican/pull/1618#issuecomment-106199264>.
>


-- 

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by justinmayer** [comment]
@ionelmc: Is there an advantage to relocating the tests to `/pelican_tests` as opposed to `/tests`? The latter appears to be a more common pattern.

**Comment by ionelmc** [comment]
@justinmayer The advantage was me not having to rework all the imports in the tests :-)

I can redo this, and have them in a `tests` directory but you have to pledge that you merge this.

**Comment by justinmayer** [comment]
Already planning on merging it, as noted by the 3.6.1 milestone I added last week. When you rebase on current master and make your changes, would you take a moment to squash into discrete commits?

Really appreciate all your help with this. It'll be nice to resolve the aforementioned problems related to this issue.

**Comment by ionelmc** [comment]
I don't think I can rebase this. Git not smart enough to deal with renames in rebase - I have to redo it.

**Comment by justinmayer** [comment]
Good point. Thanks again for all your assistance with this effort.

**Comment by justinmayer** [comment]
Hi @ionelmc. Just checking in... Any chance you might find the time to implement the changes we talked about a couple weeks ago?

**Comment by ionelmc** [comment]
Ok. Figured out a smarter (or simpler) fix in #1778.

**Pull request closed without merging**
