### PR TITLE
Fix documentation build and some fixes

### PR DESCRIPTION
**Pull request by pauloxnet**
# Pull Request Checklist

Resolves: #issue-number-here 

- [x] Ensured **tests pass** and (if applicable) updated functional test output
- [ ] Conformed to **code style guidelines** by running appropriate linting tools
- [ ] Added **tests** for changed code
- [x] Updated **documentation** for changed code

### CODE REVIEW

**Comment by justinmayer** [comment]
Hey Paolo! I'm so very sorry for the delay in merging your contribution. Would you be so kind to rebase on current `master` and resolve the conflicts so we can get this merged?

**Comment by pauloxnet** [comment]
Hi Justin, I'll be back in a week and I'll rebase this PR

**Comment by justinmayer** [comment]
Hey Paolo! Any chance you could resolve the conflicts in your PR? 😊

**Comment by pauloxnet** [comment]
Hi @justinmayer I think I resolved all conflicts ion this PR now

**Comment by justinmayer** [comment]
It seems like Sphinx is throwing a warning (treated as error) in the documentation build step. Could you take a look and see how it might be resolved?

**Comment by pauloxnet** [comment]
> Could you take a look and see how it might be resolved?

@justinmayer I resolved the Sphinx warning in the documentation build step.

**Comment by justinmayer** [comment]
Thank you for the enhancements, Paolo! 🌟

**Pull request merged**
