### PR TITLE
Add a new signal: page_generator_write_page

### PR DESCRIPTION
**Pull request by skz169**

### CODE REVIEW

**Comment by justinmayer** [comment]
Thank you for the contribution, Sergei. Would you be so kind as to provide some use cases for this new signal? Just curious what it might be used for. Thanks!

**Comment by skz169** [comment]
Hi Justin. I use this signal along with article_generator_write_article in my i18n plugin to define additional metadata.

**Comment by justinmayer** [comment]
Thanks for the additional information, Sergei.

Any comments on this from @getpelican/reviewers?

**Comment by justinmayer** [comment]
Thanks to @skz169 for the contribution and to @avaris for the review!

**Pull request merged**
