### PR TITLE
Setting "modified:" from "date:" when the latter was set from the filesystem

### PR DESCRIPTION
**Pull request by galaxy4public**
Sets the `modified:` metadata from `date:` if the user asked us
to use the filesystem for determining timestamps.

Please see discussion in #2497 .

### CODE REVIEW

**Comment by galaxy4public** [comment]
The introduced change is still in line with the [official documentation](https://docs.getpelican.com/en/stable/content.html#file-metadata) that states:
```
modified should be last time you updated the article, and defaults to date if not specified.
```

**Comment by avaris** [comment]
Tests please :).

**Comment by galaxy4public** [comment]
I will try to come up with some in the next 15 minutes or so :)

**Comment by galaxy4public** [comment]
It turned out to be quite difficult since I could not find any tests in the current test suite that do check on the filesystem metadata.  I am thinking about where to put the tests in (right now, I am thinking about working with the default reader, since the change I introduced is not related to any particular reader).

**Comment by galaxy4public** [comment]
OK, now that I introduced 4 additional files, it seems that I need to fix all these unrelated to my change tests which are using the test content directory for working with list of articles :(

**Comment by avaris** [comment]
You could create files in a temp folder to test, and it would've been probably easier that way.

**Comment by avaris** [comment]
e.g.:

```python
def create_content(path, date=None, modified=None):
    with open(path, 'w') as f:
        f.write('<html><head>\n')
        if date is not None:
            f.write('<meta name="date", content="{:%Y-%m-%d %H:%M}" />'.format(date))
        if modified is not None:
            f.write('<meta name="modified", content="{:%Y-%m-%d %H:%M}" />'.format(date))
        f.write('</head></html>\n')

folder = tempfile.mkdtemp()
path = os.path.join(folder, 'content.html')
# test with various combinations of date and modified
create_content(path, date=..., modified=...)
# ...
# cleanup
shutil.rmtree(folder)
```

**Comment by galaxy4public** [comment]
Should I rework the tests, or was it for my future PRs? ;)

**Comment by avaris** [comment]
Well... This is OK as is, even though the number of "super articles" is getting somewhat out of hand. But I wouldn't say "no" if you wanted to refactor these tests :).

**Comment by galaxy4public** [comment]
@avaris , let's agree on me refactoring it a bit later (I promise I will!).  It is just 2am on Monday here and work starts at 9am :).  I only can reliably allocate time during weekends :(.

I think the current state allows this to be merged as is.  I am learning more and more about the codebase, so the quality should step up over the time.

**Comment by justinmayer** [comment]
Many thanks to those who made this possible:
* @Kristinita for reporting
* @galaxy4public for implementing the feature and adding tests
* @avaris for reviewing

Bravo! 👏

**Pull request merged**
