### PR TITLE
Simplify feed ID generation and support URL fragments

### PR DESCRIPTION
**Pull request by Scheirle**
Changes:
- Simplified the  unique_id generation of a feed item
  - The new ids contain now two `/` more, one at the beginning of the path section and one at the end.
  - The new ids also support now url fragments (e.g. An entry located at `http://test.de/index.html#fragment` gets now the id `tag:test.de,{date}:/index.html/fragment` instead of `tag:test.de,{date}:index.html`)
- Updated unittest output to match the new ids

TODO:
- [x] Update `get_tag_uri`: https://github.com/getpelican/feedgenerator/pull/4
- [x] Wait for #1937 (no technical reason; it's just easier for everyone)
- [x] Wait for feedgenerator 1.9
- [x] Update the test output with the new ids

### CODE REVIEW

**Comment by justinmayer** [comment]
@Scheirle: What do you think about modifying `get_tag_uri` such that it only adds a slash when it's appropriate to do so?

Please accept my sincere apologies for the absurdly long delay in responding!e

**Comment by Scheirle** [comment]
> What do you think about modifying get_tag_uri such that it only adds a slash when it's appropriate to do so?

Yeah that is probably the right way to do it.

**Comment by justinmayer** [comment]
Corresponding feedgenerator pull request merged!

**Comment by justinmayer** [comment]
Checked off another box in the above list. 🎊

**Comment by Scheirle** [comment]
Finally this can be merged!

* feedgenerator 1.9 got released
* I updated the test output

It would save work (Avoid further merge conflicts) if this gets merged before https://github.com/getpelican/pelican/pull/1989 resolves it merge conflicts.

**Comment by justinmayer** [comment]
Any other @getpelican/reviewers care to review this before it is merged?

**Comment by ionelmc** [comment]
Note that this causes a regression - different ids will be generated if you upgrade pelican!

**Comment by ionelmc** [comment]
This means all your items will get republished wherever they are consumed, an undesirable consequence (annoying feed spam).

**Pull request merged**
