### PR TITLE
Implements tag cloud sorting

### PR DESCRIPTION
**Pull request by magnunleno**
For those (like me) who don't like the tag cloud to be randomly organized, I've implemented some sorting options:

* Alphabetically;
* Alphabetically Reverse (descending);
* Size;
* Size Reverse (descending);
* Random.

### CODE REVIEW

**Comment by ingwinlu** [comment]
Hi,
this was always possible in themes, i.e. jinja2's build in [sort](http://jinja.pocoo.org/docs/dev/templates/#sort) filter.

Might be worth adding this as a plugin instead of an addition to pelican.

**Comment by magnunleno** [comment]
Hi,

Despite it being possible to implement it in themes (as I used to do in my site), it will cause the site's building time to grow considerably. Since the sorting will be done in the theme, the tag cloud list sorting will be repeatedly executed for **every generated page**. Nowadays my site has something around 2000 pages, and it's taking 180~190 seconds to compile. With this feature implemented my site build time went down to 30~40 seconds.

Thanks anyway.

**Comment by ingwinlu** [comment]
set in my `base.html`
```
{% set tag_cloud = tag_cloud|sort(attribute='0')%}
{% set tag_cloud_rev = tag_cloud|sort(attribute='0',reverse=True)%}
{% set tag_cloud_size = tag_cloud|sort(attribute='1')%}
{% set tag_cloud_size_rev = tag_cloud|sort(attribute='1',reverse=True)%}
{% macro list_tag_cloud(tags) -%}
<ul>
    {% for tag in tags %}
        <li class="tag-{{ tag.1 }}">
            <a href="{{ SITEURL }}/{{ tag.0.url }}">
                {{ tag.0 }}
            </a>
        </li>
    {% endfor %}
</ul>
{%- endmacro %}
```

used like this in `tags.html`:  [here](https://www.heroicdebugging.biz/tags.html) (only quickly hacked it together, i don't use a tag list usually)
```
{% block content %}
<div class="row">
    <div class="col-lg-12">
    <h2>tag_cloud</h2>
    {{ list_tag_cloud(tag_cloud)}}
    <h2>tag_cloud_rev</h2>
    {{ list_tag_cloud(tag_cloud_rev)}}
    <h2>tag_cloud_size</h2>
    {{ list_tag_cloud(tag_cloud_size)}}
    <h2>tag_cloud_size_rev</h2>
    {{ list_tag_cloud(tag_cloud_size_rev)}}
    </div>
</div>
{% endblock %}
```
no noticable slowdown on a rpi, 125s vs 130s
`Done: Processed 37 article(s), 1 draft(s) and 1 page(s) in 129.08 seconds.`

then again, there is use in having this functionality as a *plugin*.

**Comment by magnunleno** [comment]
Setting it in `base.html` is even worse, it will sort the tag_cloud even when it isn't needed. In my theme I set the sorting to occur only when the tag cloud is included.

Your haven't had any noticeable slowdowns because you have a "small" site. My site has nearly 180 articles and something around 400 tags.

**Comment by ingwinlu** [comment]
ah i thought the jinja environment would take care of caching then

**Comment by magnunleno** [comment]
As far as I'm concerned it doesn't cache, since the tagcloud is altered and is never "written back" to the context that pelican uses.

**Comment by ingwinlu** [comment]
that might be worth considering together with #1566.

feel like it needs tests even though you are basically just testing the build in sorting function.

**Comment by avaris** [comment]
Maybe `tag_cloud` should become a plugin.

**Comment by ingwinlu** [comment]
that certainly is an even better way forward

**Comment by iKevinY** [comment]
I agree with turning `tag_cloud` into a plugin, since tag clouds aren't really a core feature for blogs, nor are they relevant at all to regular static sites.

**Comment by ingwinlu** [comment]
I will prepare a PR then

**Comment by ingwinlu** [comment]
@justinmayer pewpew here as well

**Comment by justinmayer** [comment]
Since tag clouds are now out of core and implemented via a plugin, it would appear this pull request is no longer relevant. (Thanks for the reminder, @ingwinlu.)

**Pull request closed without merging**
