### PR TITLE
pelican-quickstart: switch to jinja2

### PR DESCRIPTION
**Pull request by ix5**
As per request by @justinmayer on issue #2000, to omit unused build targets and allow for more powerful templating.

- Use the jinja2 templating language for Makefile, fabfile,
  pelicanconf, publishconf, and develop-server.sh
- Add logic in pelican_quickstart.py
- Let jinja2 handle opening and reading template files
- Remove thus unused functions for string.Template

### CODE REVIEW

**Comment by ix5** [comment]
Do we really need to make flake8-import-order happy?
They say this about themselves:
> This plugin is under somewhat active development and is heavily influenced by the personal preferences of the developers of cryptography. Expect seemingly random changes and configuration changes as we figure out how it should work.

**Comment by ix5** [comment]
Closing due to inactivity

**Comment by justinmayer** [comment]
Apologies, @ix5. It's been a busy year.

Any @getpelican/reviewers have a moment to review this pull request?

**Comment by ix5** [comment]
Heh, I saw the growing backlog of issues and PRs, didn't want to keep it that way and closed this one.

Anyway, I've rebased off master, fixed conflicts, should be good to go. Travis gives the go-ahead as well.

Thanks for keeping this project running, @justinmayer, you're a treasure. And thank you @iKevinY as well!

**Comment by ix5** [comment]
Hey @iKevinY @justinmayer  could you please merge this?

**Comment by justinmayer** [comment]
Many thanks, @ix5, for your contribution, kind words, and patience. And thanks to @iKevinY for reviewing!

**Pull request merged**
