### PR TITLE
Use Furo as Sphinx documentation theme

### PR DESCRIPTION
**Pull request by pauloxnet**
In this PR I used the Sphinx documentation theme [Furo](https://github.com/pradyunsg/furo) , the same theme used by [urllib3](https://urllib3.readthedocs.io) and [others](https://github.com/pradyunsg/furo#used-by).

### CODE REVIEW

**Comment by pauloxnet** [comment]
# Screenshots
## Big
### Light
big-light
### Dark
big-dark
## Small
### Light
small-light
### Dark
small-dark

**Comment by pauloxnet** [comment]
Any comments about this new sphinx theme for a modern documentation ?

**Comment by pauloxnet** [comment]
> I have used Furo in other projects, and it is indeed an attractive theme for documentation. I built the Pelican documentation with Furo and reviewed it, and it looks nice enough to me.
> 
> Any thoughts from @getpelican/reviewers?

**Comment by justinmayer** [comment]
@pauloxnet: Great work on this, Paolo! Thank you SO much for your contribution and particularly for your patience.

I made a few modifications via follow-up commits and pushed them to PR #3023. Would you please take a moment to review that PR and let me know if you have any comments before I merge it?

**Comment by pauloxnet** [comment]
> @pauloxnet: Great work on this, Paolo! Thank you SO much for your contribution and particularly for your patience.
> 
> I made a few modifications via follow-up commits and pushed them to PR #3023. Would you please take a moment to review that PR and let me know if you have any comments before I merge it?

I'm glad you liked my proposal to use Furo for Pelican's documentation.

I go immediately to review your PR and close this PR with this comment.

**Pull request closed without merging**
