### PR TITLE
More Whitespace

### PR DESCRIPTION
**Pull request by W7PEA**
Moved parser.add_argument params to a newline to hopefully make flake happy.

### CODE REVIEW

**Comment by justinmayer** [comment]
Hi Patrick. Your contributions are appreciated.

As a point of order, please, please do not close pull requests and then submit new ones. Doing so is unnecessary and just creates a lot of clutter.

The first step it making your changes on a new branch instead of `master`, as mentioned in our [Contributing docs](http://docs.getpelican.com/en/stable/contribute.html) and elaborated on our [Git Tips](https://github.com/getpelican/pelican/wiki/Git-Tips#squashing-commits) page, and then issuing your pull request from that branch.

Then, if there is a problem, you can rebase **instead** of constantly closing and opening new pull requests.

**Comment by justinmayer** [comment]
Also: please run `flake8` before making your commits instead of relying on Travis to do those checks for you.

**Comment by W7PEA** [comment]
I'm not a developer by trade so you're getting my best efforts here on what should have been a trivial change. I'm not setup to run all these tools on my laptop as I don't normally need\use them in my work. But I wanted to get my fix as passing as possible so that at least the only thing that was failing was the test issues related to the framework change, unfortunately I did that in a way that was messy for you. Sorry about that.
I didn't know that closing and resubmitting was the wrong approach. I'll read up on that. 
Thanks for the feedback, I always love to learn new things!

Thanks,-p
Date: Tue, 19 Jan 2016 11:45:00 -0800

**Comment by W7PEA** [comment]
Thanks for the feedback @justinmayer. I don't use the same tools as you in my normal work so it seemed overkill to do all that for such a trivial change, but yes apparently I was wrong about that. ;-)

This PR now passes all the code analysis tests. The failed tests are all the same the ones failing in earlier PRs and as mentioned seem to be because of a change in the tool used in the tests.

Sorry for the messy contribution.

**Comment by ingwinlu** [comment]
No, this test breaks importer behaviour; you define two output argparse arguments but deleted another unrelated one.

**Comment by W7PEA** [comment]
I'm sorry. I'm not following your comment. If you look at the /pelican_import.py the only change is to the default value on the --output argument and the help text. The other changes are in the docs not in code.  Is that what you were referring to?

**Comment by W7PEA** [comment]
OK, I see it. Cut n paste issue when trying to clean up the whitespace for Flake8.  I'll resubmit.

**Comment by W7PEA** [comment]
I started over, followed the steps this time. I believe this PR can be closed now in favor of this one: 
https://github.com/getpelican/pelican/pull/1899

**Comment by W7PEA** [comment]
This is not the correct PR for this change any longer. I later submitted a change where I followed the rules.

**Pull request closed without merging**
