### PR TITLE
Add a temporary_locale context manager. Addresses #1347.

### PR DESCRIPTION
**Pull request by alexwlchan**
Code is taken directly from the original description of the issue, plus a few places in the tests where I spotted it could be used immediately.

Tests passing locally, plus a test for the new code.

### CODE REVIEW

**Comment by alexwlchan** [comment]
(Note to self: if/when this is resolved, go back and pick up the work on parameterised tests)

**Comment by justinmayer** [comment]
Would any @getpelican/reviewers care to review this pull request? Many thanks in advance!

**Comment by justinmayer** [comment]
Following up on my request to @getpelican/reviewers... Anyone care to review this pull request?

**Comment by alexwlchan** [comment]
Closing due to inactivity.

**Pull request closed without merging**
