### PR TITLE
Improve notmyidea theme

### PR DESCRIPTION
**Pull request by jorgesumle**
It solves #2178 and removes the trailing white spaces from the CSS files.

### CODE REVIEW

**Comment by avaris** [comment]
You need to regenerate the test output.

**Comment by jorgesumle** [comment]
Ping. Can someone review it?

**Comment by justinmayer** [comment]
Many thanks for the enhancements, Jorge!

**Comment by jorgesumle** [comment]
Great! @josch, can you close https://github.com/getpelican/pelican/issues/2178?

**Pull request merged**
