### PR TITLE
Add css for figures under .rst

### PR DESCRIPTION
**Pull request by mixmastamyk**
For #2113

### CODE REVIEW

**Comment by iKevinY** [comment]
Thanks for the PR, @mixmastamyk! Some of Pelican's tests check to make sure that the generated and expected output files are identical. Since you've made some changes to `main.css`, you'll need to [update the expected output](http://docs.getpelican.com/en/stable/contribute.html#running-the-test-suite) to get those tests to pass.

**Comment by mixmastamyk** [comment]
I ran the three commands and got a lot of warnings and errors.  Also git thinks dozens of files have changed, but none are .css.  

This is a bit more than I bargained for, just wanted to add a missing class or two.

**Comment by iKevinY** [comment]
Since you've only made changes to CSS, I think you can actually get away with just copying the new version of `main.css` to these locations:

- `pelican/tests/output/basic/theme/css/main.css`
- `pelican/tests/output/custom/theme/css/main.css`
- `pelican/tests/output/custom_locale/theme/css/main.css`

**Comment by justinmayer** [comment]
@mixmastamyk: Any chance you could address the errors in the functional test output so we can merge your contribution?

**Comment by mixmastamyk** [comment]
Sorry, I haven't looked at this in a year and haven't used pelican since.  Y'all are free to copy my ten lines of css and use them or close this out.

**Comment by justinmayer** [comment]
@mixmastamyk: No worries. Addressed via 021f1525. Many thanks for the assistance.

**Pull request closed without merging**
