### PR TITLE
Fixing some warnings and errors in the sample content.

### PR DESCRIPTION
**Pull request by marespiaut**
The current sample content is not up-to-date with the current Pelican mechanism.

This will help new comers to understand better how Pelican works.

* More valid articles.
* More translations.
* Images are now correctly displayed.

### CODE REVIEW

**Comment by avaris** [comment]
Looks like you need to [regenerate the sample output](http://docs.getpelican.com/en/stable/contribute.html#running-the-test-suite).

PS: For future, it's best to run tests locally before pushing.

**Comment by marespiaut** [comment]
Alright, I didn't knew that. I'll try to fix it.

**Comment by justinmayer** [comment]
Hi @marespiaut. Would you be so kind as to re-generate the sample output and include it in your PR so we can get your contribution merged?

**Comment by justinmayer** [comment]
Thank you for the impetus to fix this, @marespiaut. Very much appreciated! 🙇

**Pull request closed without merging**
