### PR TITLE
Fix empty page listing for default/notmyidea theme (issue #2097)

### PR DESCRIPTION
**Pull request by hartwork**
Issue #2097 still needs a fix, here's a patch. Would be cool to have this fixed. Thank you!

### CODE REVIEW

**Comment by avaris** [comment]
Duplicate #2149

**Comment by hartwork** [comment]
I's not a duplicate, #2149 does not touch `[..]/templates/index.html`.

**Comment by hartwork** [comment]
Also, while #2149 is open, that commit is on `master` and in releases already:
```
# git tag --contains ec5c77b25145f7c20fee24c6b85b478295dbc956
3.7.0
3.7.1
```

**Comment by hartwork** [comment]
You're right. If you can speed that one up, that would be awesome. Closing.

**Pull request closed without merging**
