### PR TITLE
Translate documentation into Simplified Chinese

### PR DESCRIPTION
**Pull request by GeorgeHu6**
# Pull Request Checklist

- [x] Ensured **tests pass** and (if applicable) updated functional test output
- [x] Conformed to **code style guidelines** by running appropriate linting tools
- [x] Added **tests** for changed code
- [x] Updated **documentation** for changed code

### CODE REVIEW

**Comment by justinmayer** [comment]
Hi George. Are the translations fully up-to-date with documentation in the current `main` branch? Including, for example, the documentation addition in #2761?

**Comment by GeorgeHu6** [comment]
Yes, all of the translations are fully up-to-date.

**Comment by justinmayer** [comment]
Excellent! If I may ask, how do you intend to ensure that the translation stays in-sync and up-to-date with documentation changes in the future? Just curious! 😊

**Comment by GeorgeHu6** [comment]
At present, I will manually check the update of the doc. Recently, I have been working on my workflow system which makes it possible to keep me informed of doc updates.

**Comment by justinmayer** [comment]
Given that I have never used Sphinx in a multilingual context, could you let me know the exact steps needed to build and view the Chinese version of the Pelican documentation?

**Comment by GeorgeHu6** [comment]
OK, Chinese version of documentation can be built as following steps:

1. download all the `po` files to `docs/locale/zh_CN/LC_MESSAGES`
2. Run `sphinx-build -b html -D language=zh_CN . ./_build/html/zh_CN/` in folder `docs` (make sure `locale_dirs = ["locale/"]` has been set in `conf.py`) and all of the translated HTML files will be generated in `docs/_build/html/zh_CN` .

**Comment by justinmayer** [comment]
Thank you, George. Here are the (slightly modified) steps I took to locally view the Chinese documentation:

```fish
cd ~/Projects/pelican/
gh pr checkout 3346
cd docs
sphinx-build -b html -D language=zh_CN . ./_build-zh_CN/
python -m http.server -d _build-zh_CN
```

… after which I was able to view the Chinese documentation at: http://localhost:8000 🎉 

I don't understand exactly what is required on the ReadTheDocs side of the equation, although it is possible that the only necessary step is to create a separate `pelican-zh_CN` RtD project and associate it with Chinese, as documented here: https://docs.readthedocs.io/en/stable/localization.html#projects-with-multiple-translations-sphinx-only

**Comment by GeorgeHu6** [comment]
Yeah, it is very convenient to add a translation version of project in RtD. After doing some tests in my own RtD account, I came up with a way to add a translation to an existing RtD project:

1. Create a new RtD project and make sure the project meet the following requirements:
	- set `locale_dirs` in `conf.py` 
	- translated `po` files in the directory which set by `locale_dirs`
	- set the language of RtD project as "Simplified Chinese"
2. After the new RtD project is built, add the new project to the "Translations" section of original project

**Comment by GeorgeHu6** [comment]
Sure, Chinese translation of the documentation is totally up to date now.

**Review by justinmayer — APPROVED** [review]
Many thanks for all your work on this translation, George. I am pleased to add this to Pelican. Much appreciated! 🥇

**Comment by justinmayer** [comment]
Translation is now live! 🎉  <https://docs.getpelican.com/en/latest/> ➡️ (tap [Flyout Menu][]) ➡️ Languages ➡️ [`zh-cn`](https://docs.getpelican.com/zh-cn/latest/)


[Flyout Menu]: https://docs.readthedocs.io/en/stable/flyout-menu.html

**Comment by GeorgeHu6** [comment]
Yeah! Thank you all guys. I will try to keep the Chinese translation up to date.

**Pull request merged**
