### PR TITLE
Add AsciiDoc example

### PR DESCRIPTION
**Pull request by marco-m**
Following discussion for issue 488 of pelican-plugins (https://github.com/getpelican/pelican-plugins/issues/488)

### CODE REVIEW

**Comment by Scheirle** [comment]
As the AsciiDoc reader is a plugin in my opinion the documentation for it should be with the plugin and not the pelican core. For example in its readme file.

**Comment by justinmayer** [comment]
I must agree with @Scheirle here.

**Comment by marco-m** [comment]
Fair enough. Will open a PR against the plugins repo.

**Comment by marco-m** [comment]
Replaced by https://github.com/getpelican/pelican-plugins/pull/783

**Pull request closed without merging**
