### PR TITLE
Improve exception logging a bit more. Now it always dumps a traceback…

### PR DESCRIPTION
**Pull request by ionelmc**
…. Ref: #1717, #1718.

### CODE REVIEW

**Comment by avaris** [comment]
Well... Also dumps same traceback "a bit more". 

* For `-D` mode same traceback is shown twice (1 with logging, 1 with `raise`)
* For `--autoreload` + `-D` mode same traceback is shown three times (2 with logging, 1 with `raise`)

**Comment by ingwinlu** [comment]
whats the status on this? I would like to have that resolved asap (even if that means removing #1717)

**Comment by ionelmc** [comment]
It dumps trace back too many times. I'm a bit lost here how to fix that.

On Thursday, May 28, 2015, winlu <notifications@github.com> wrote:

> whats the status on this? I would like to have that resolved asap (even if
> that means removing #1717
> <https://github.com/getpelican/pelican/issues/1717>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getpelican/pelican/pull/1723#issuecomment-106198462>.
>


-- 

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by avaris** [comment]
There is nothing to fix. I don't see the point of dumping traceback always. That's what `--debug` is for.

**Comment by ingwinlu** [comment]
@justinmayer this can be closed #1743

**Pull request closed without merging**
