### PR TITLE
Support templates of any file extension

### PR DESCRIPTION
**Pull request by naturallymitchell**
Re: https://github.com/getpelican/pelican/issues/1162

### CODE REVIEW

**Comment by justinmayer** [comment]
Hey Mitch. Looks like there are some test errors related to your pull request. Would you look into them and see if you can resolve, rebase, and squash your commits?

**Comment by justinmayer** [comment]
Hi Mitchell. Just following up on your pull request. Any chance you could take a look and see what needs to be done to resolve the test failure?

**Comment by justinmayer** [comment]
Hey Mitchell. Just following up one last time. Any chance you could take a look and see what needs to be done to resolve the test failure on your pull request?

**Comment by mitchtbaum** [comment]
I still need to look at a lot more code to understand how deep this would affect interrelated subsystems.  This change seems like it would require further generalization of a few layers of functionality.  I bet that we have several tests and possibly some generator functions that could merge and handle their responsibilities together.  (Tangentially?,)  This change dovetails with my plans for theme inheritance, because, for instance with RSS Generator, we could use Pelican's own template-driven, plugin-enhanced generator instead of ```feedgenerator.py```, as long as we have a simple feed template and can update tests that currently expect that specific code to run and we have an easy way to reuse that template across themes.

**Comment by justinmayer** [comment]
There is now a `TEMPLATE_EXTENSIONS` setting that delivers this functionality.

**Pull request closed without merging**
