### PR TITLE
Don't store a RichHandler object in the `argparse` namespace (#3394)

### PR DESCRIPTION
**Pull request by cpitclaudel**
Resolves: #3394 

- [x] Ensured **tests pass** and (if applicable) updated functional test output
- [x] Conformed to **code style guidelines** by running appropriate linting tools
- [ ] ~Added **tests** for changed code~
- [ ] ~Updated **documentation** for changed code~

Unfortunately I can't test locally, but this patch should be harmless, at least.

### CODE REVIEW

**Comment by snh** [comment]
I too was getting the error described in #3394 and can confirm this patch fixes the issue for me.

**Comment by justinmayer** [comment]
Thanks, Clément! Do you think it's worth adding a test that fails for MacOS images in CI when this change is not present?

**Comment by cpitclaudel** [comment]
A regression test would be nice, yes.  I suppose the best way to go about it would be to start the file watcher and then stop it a few seconds later somehow, asserting that it didn't crash in the meantime?

**Review by justinmayer — APPROVED** [review]
Many thanks for the fix, Clément. I'm going to merge this now so that we can release a fix for this and thereby eliminate the problem for end users as soon as possible. If you think of one or more unit tests that might prevent future regressions, submitting them in a follow-up pull request would be most appreciated. Thanks again!

**Pull request merged**
