### PR TITLE
Convert Wordpress caption to figure

### PR DESCRIPTION
**Pull request by mart-e**
In Wordpress, inserting image with a caption can look like 
```
[caption id="attachment_42" caption="Image Description"]<a ...><img ... /></a>[/caption]
[caption id="attachment_42"]<a ...><img ... /></a> Image Description[/caption]
[caption id="attachment_42"]<img ... > Image Description[/caption]
```

Replace by an HTML `<figure>` tag

### Pull Request Checklist

- [x] Ensured **tests pass** and (if applicable) updated functional test output
- [x] Conformed to **code style guidelines** by running appropriate linting tools
- [x] Added **tests** for changed code
- [ ] Updated **documentation** for changed code

PS: feel free to suggest a better regex, this was [tested with a few examples](https://regex101.com/r/oTyq6b/1) taken from my blog.

### CODE REVIEW

**Comment by mart-e** [comment]
Don't get why the build is failing... When raising an error to see ouput, it's as if 1b360acafaa126ee52ca8472e816ec3f994c7c02 was not merged :thinking: 
https://github.com/getpelican/pelican/actions/runs/5169977273/jobs/9312580636

**Comment by justinmayer** [comment]
It seems clear that https://github.com/getpelican/pelican/commit/1b360acafaa126ee52ca8472e816ec3f994c7c02 was indeed merged. It appears in `master` as well as in the branch attached to this PR: https://github.com/mart-e/pelican/commits/wp-caption-to-figure

**Comment by mart-e** [comment]
@justinmayer ok after a lot more debugging, I finally understood, it's due to the pandoc version used in github actions (2.9.2) being different than the one on my machine (3.0.1).

If you check the output in the action below, you see that
```html
<p><figure>
<img src="/theme/img/xpelican.png.pagespeed.ic.Rjep0025-y.png"/>
<figcaption>This is a pelican</figcaption>
</figure></p>
```
is converted using `pandoc -f html+raw_html --to=gfm-smart --wrap=none` and results in:
```md
![This is a pelican](/theme/img/xpelican.png.pagespeed.ic.Rjep0025-y.png)
```
https://github.com/mart-e/pelican/actions/runs/5174375780/jobs/9320618059#step:8:78

I may have been a bit optimistic on #3114 solving all issues.

Only pandoc 3.0 has a proper support for `<figure>` tags:
https://pandoc.org/releases.html#pandoc-3.0-2023-01-18
```
Markdown writer: figures are output as implicit figures if possible, via HTML if the raw_html extension is enabled, and as Div elements otherwise.
HTML reader: <figure> elements are parsed as figures, with the caption taken from the respective <figcaption> elements.
```

The easiest for my issue would be to upgrade the required vrsion of pandoc but it's probably not the best as even [the latest ubuntu](https://packages.ubuntu.com/lunar/pandoc) is still in 2.17.

I see two better solutions:

- modify my test to be a bit less strict and must check that `[caption]` tags are converted (to whatever pandoc allows)
- instead of using `<figure>...<figcaption>Caption Text</figcaption></figure>`, I convert to an `<p></p><p>Caption Text</p>`

I tend to prefer the first one but it brings a different result based on the version of pandoc installed.

Let me know if ok with you.

**Comment by justinmayer** [comment]
I agree that the first option sounds better. 👍

**Review by justinmayer — APPROVED** [review]
Many thanks for your work on this, Martin. We can revisit this topic once Pandoc 3.0+ is ubiquitous, but until then your solution strikes a good balance. 👍

**Pull request merged**
