### PR TITLE
Docs: Note how posts are published when 'draft' is default

### PR DESCRIPTION
**Pull request by abackstrom**
The docs show how posts can be defaulted to "draft" mode, but not how to publish a post when your site is in this state.

### CODE REVIEW

**Comment by justinmayer** [comment]
I believe one can also remove the `Status: draft` line altogether, no?

**Comment by iKevinY** [comment]
I think the PR intends to clarify how to publish a post if the user has set `draft` as the default `status` via `DEFAULT_METADATA` in Pelican's configuration.

**Comment by justinmayer** [comment]
Ah, that makes sense. Thanks for pointing me in the right direction, Kevin.

**Comment by iKevinY** [comment]
@justinmayer No problem!

**Comment by justinmayer** [comment]
Thanks for the clarification, Annika!

**Pull request merged**
