### PR TITLE
RFC - pelican-import, fix urls of attached files

### PR DESCRIPTION
**Pull request by stuaxo**
Don't merge this yet - this probably needs some tweaks..

With this patch wp-attach modifies ```<img``` and  ```<a href``` urls to point at the attachment path - so  ```http://example.com/wp-content/uploads/blah.png```   becomes    ```wp-content/uploads/blah.png```

This needs wp-content in pelicanconf STATIC_FILES

I thought I could use {filename} but since the importer is generates source html this doesn't work.
It would be nice if there was a way to customise the output path, but not sure how that would work.

### CODE REVIEW

**Comment by hitrust** [comment]
very nice!

**Comment by stuaxo** [comment]
Apologies for the many commits, I've been tweaking this in the web editor!

**Comment by stuaxo** [comment]
I should probably fix the URLs after the content has been converted by pandoc whatever format to ```{filename}path/to/file```.

This has the advantage that the code will get a little simpler too.

**Comment by stuaxo** [comment]
This now changes the url to have a leading slash: ```{filename}/path/to/file``` and works with files generated by pandoc.

**Comment by stuaxo** [comment]
I'm going to see if I can extract the functionality as a set of smaller PRs

**Comment by oulenz** [comment]
I wonder whether this functionality hasn't already been added by https://github.com/getpelican/pelican/pull/2380? (BTW, sorry for not referencing this PR, I hadn't seen it at the time.)

**Comment by stuaxo** [comment]
Mostly, the thumbnails aren't getting fixed up, but I'm looking into it.

I'm going to close this PR, as I think between the but you linked, the smaller PRs this should all be covered.

**Pull request closed without merging**
