### PR TITLE
Improve internal error reporting. Fixes #1717.

### LINKED ISSUE #1717: -D (debug mode) doesn't show any trackbacks on internal exceptions
Also, exceptions are rendered using `str` instead of `repr`, making this worse than it already is.

### PR DESCRIPTION
**Pull request by ionelmc**

### CODE REVIEW

**Comment by avaris** [comment]
Was `exc_info=True` really necessary? `raise` will already re-raise the exception and give full traceback. Now the traceback will be outputted twice.

**Comment by ionelmc** [comment]
@avaris in my tests is never does

**Comment by avaris** [comment]
@ionelmc how are you testing? This is what i get:
```
$ pelican content -s pelicanconf.py -D --autoreload

[skipped unrelated parts]

CRITICAL: Internal failure: u"'ArticlesGenerator' object has no attribute 'non_existing_attribute'"
  |___
  | Traceback (most recent call last):
  |   File "/home/avaris/workspace/python/pelican/pelican/__init__.py", line 437, in main
  |     pelican.run()
  |   File "/home/avaris/workspace/python/pelican/pelican/__init__.py", line 169, in run
  |     p.generate_context()
  |   File "/home/avaris/workspace/python/pelican/pelican/generators.py", line 597, in generate_context
  |     signals.article_generator_finalized.send(self)
  |   File "build/bdist.linux-x86_64/egg/blinker/base.py", line 267, in send
  |     for receiver in self.receivers_for(sender)]
  |   File "/home/avaris/workspace/test/test_pelican/some_plugin.py", line 4, in fnc
  |     x = generator.non_existing_attribute
  | AttributeError: 'ArticlesGenerator' object has no attribute 'non_existing_attribute'
CRITICAL: 'ArticlesGenerator' object has no attribute 'non_existing_attribute'
Traceback (most recent call last):
  File "/home/avaris/.virtualenvs/pelican-py2.7/bin/pelican", line 9, in <module>
    load_entry_point('pelican==3.5.0', 'console_scripts', 'pelican')()
  File "/home/avaris/workspace/python/pelican/pelican/__init__.py", line 437, in main
    pelican.run()
  File "/home/avaris/workspace/python/pelican/pelican/__init__.py", line 169, in run
    p.generate_context()
  File "/home/avaris/workspace/python/pelican/pelican/generators.py", line 597, in generate_context
    signals.article_generator_finalized.send(self)
  File "build/bdist.linux-x86_64/egg/blinker/base.py", line 267, in send
  File "/home/avaris/workspace/test/test_pelican/some_plugin.py", line 4, in fnc
    x = generator.non_existing_attribute
AttributeError: 'ArticlesGenerator' object has no attribute 'non_existing_attribute'
```

Plus, using `%r` or `%s` doesn't do much because the internal logger (`log.py`) already stringifies exceptions.

**Comment by ionelmc** [comment]
Eg, if I make Generator's generate_feeds method fail i get this:
```
pelican --output output --settings settings.py --delete-output-directory -D -v
CRITICAL: global name 'xxxx' is not defined
ERROR: InvocationError: 'C:\\Users\\ionel_000\\.tox\\blog.ionelmc.ro\\Scripts\\pelican.EXE --output output --settings settings.py --delete-output-directory -D -v'
```
There's no output after that.

**Comment by avaris** [comment]
If your goal was to get the exception class by using `%r`, which is perfectly reasonable by the way, you actually need to modify [this line](https://github.com/getpelican/pelican/blob/master/pelican/log.py#L152).

**Comment by avaris** [comment]
@ionelmc there are a few problems with the way you run pelican.

First, `-D` and `-v` is mutually exclusive. Last one will be active which is `-v`, and you won't get exception with that.

Second, the code you changed applies to `--autoreload` mode. I'm not sure how you expect to reach that part without using `--autoreload`.

**Comment by ionelmc** [comment]
Dooh :grin: 

I'll make another PR to fix this up.

**Comment by avaris** [comment]
:). Actually, you're fixing a bug in that line (the one I mentioned in #1692). I didn't get a chance to do that. `logger.critical(e.args)` needs to be `logger.critical('%s', e)`. If you can correct that, it would be perfect. 

Logging the exception class along with the message also makes sense to me (if you want to implement that).

**Comment by ionelmc** [comment]
Yes I will fix that too

**Comment by ionelmc** [comment]
@avaris so I made another PR (#1723 )

**Pull request merged**
