### PR TITLE
Handle empty Markdown files more gracefully.

### PR DESCRIPTION
**Pull request by wjt**
Currently, a zero-byte Markdown file in the content tree will raise IndexError; and a whitespace-only Markdown file will raise AttributeError. Here are a couple of patches to make the error output a bit friendlier.

### CODE REVIEW

**Comment by ingwinlu** [comment]
missing tests

**Comment by justinmayer** [comment]
Thanks for the enhancement, Will. As Winlu mentioned, would you please add tests for these improvements so they aren't broken by somebody else down the road?

**Comment by wjt** [comment]
Added a test, and it even passes now!

**Comment by justinmayer** [comment]
@ingwinlu / @avaris: Any comments on this pull request? Your thoughts are always much appreciated.  (^_^)

**Comment by ingwinlu** [comment]
lgtm

**Comment by avaris** [comment]
:+1:

**Comment by justinmayer** [comment]
Many thanks to @wjt for the enhancements, and to @ingwinlu, @avaris, and @iKevinY for reviewing!  (^_^)

**Pull request merged**
