### PR TITLE
Add S3 404 custom page to Tips documentation

### PR DESCRIPTION
**Pull request by jo-tham**
add 404 page instructions for amazon s3 to the docs.

### CODE REVIEW

**Comment by justinmayer** [comment]
Hi @jo-tham. Thanks for the addition to the documentation. When you make a fix-up commit, it's usually best to [squash your commits](https://github.com/getpelican/pelican/wiki/Git-Tips#squashing-commits). Would you please do that for this pull request?

**Comment by jo-tham** [comment]
Absolutely, should've done it to start with.

Is it ok to --force, or should it be a new branch?

**Comment by iKevinY** [comment]
@jo-tham `--force` is fine. It will automatically update the commits in this pull request.

**Comment by justinmayer** [comment]
Thanks for the improvement, Jotham.  (^_^)

**Pull request merged**
