### PR TITLE
Fix #2982: Improve _HTMLWordTruncator

### LINKED ISSUE #2982: SUMMARY_MAX_LENGTH is applied in a wrong way to Vietnamese content
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Ubuntu 21.10
- **Python version**: 3.10.2
- **Pelican version**: 4.7.2
- **Link to theme**: N/A, I use my self-made theme
- **Links to plugins**: None
- **Link to your site**: https://manhhomienbienthuy.github.io/
- **Link to your source**: It‘s not published.
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**:  https://gist.github.com/manhhomienbienthuy/b989f84c7551d9ff13549e260cfb9450

## Issue

When a site contains articles in Vietnamese, the summary on index page generated by pelican will be much shorter than SUMMARY_MAX_LENGTH. I use default setting for SUMMARY_MAX_LENGTH = 50, but it's obviously less than 50 words (only about 35-36 words). But the biggest problem is that, sometimes the last word is broken in the middle and only some first characters remaining. I copied generated results here, so that you can have a direct compare:

```
Bài toán FizzBuzz thì quá kinh điển rồi, có lẽ ai học lập trình cũng đã từng làm quen với bài toán này ít nhất một lần. Trong bài viết này, tôi sẽ tổng hợp một s […] 
```

When I used version 4.6.0, it had no problems. Here is the result

```
Bài toán FizzBuzz thì quá kinh điển rồi, có lẽ ai học lập trình cũng đã từng làm quen với bài toán này ít nhất một lần. Trong bài viết này, tôi sẽ tổng hợp một số các khác nhau để giải bài toán này với ngôn ngữ Python. Mục […] 
```

### PR DESCRIPTION
**Pull request by manhhomienbienthuy**
# Pull Request Checklist

Resolves: #2982 

- [x] Ensured **tests pass** and (if applicable) updated functional test output
- [x] Conformed to **code style guidelines** by running appropriate linting tools
- [x] Added **tests** for changed code
- [ ] Updated **documentation** for changed code (Not necessary)

### CODE REVIEW

**Comment by avaris** [comment]
I was thinking about this recently. I don't like the maintainability of keep adding alphabet blocks. I'm sure it is probably not generally true but can we assume anything outside DBC is latin-like (words separated by space)? That should simplify the regex with some generalizability. Something like, special casing DBC but reverting to original implementation as a fallback:

```python
    _word_regex = re.compile(r"{DBC}|(\w[\w'-]*)".format(
        # DBC means CJK-like characters. An character can stand for a word.
        DBC=("([\u4E00-\u9FFF])|"          # CJK Unified Ideographs
             "([\u3400-\u4DBF])|"          # CJK Unified Ideographs Extension A
             "([\uF900-\uFAFF])|"          # CJK Compatibility Ideographs
             "([\U00020000-\U0002A6DF])|"  # CJK Unified Ideographs Extension B
             "([\U0002F800-\U0002FA1F])|"  # CJK Compatibility Ideographs Supplement
             "([\u3040-\u30FF])|"          # Hiragana and Katakana
             "([\u1100-\u11FF])|"          # Hangul Jamo
             "([\uAC00-\uD7FF])|"          # Hangul Compatibility Jamo
             "([\u3130-\u318F])"           # Hangul Syllables
             )), re.UNICODE)
```

If I remember correctly, this was producing correct results but I didn't test extensively. Mainly because I don't speak Vietnamese, so I wasn't sure about my tests being proper :).

**Comment by manhhomienbienthuy** [comment]
@avaris 
Thanks for your comments. I completely agree with you that we can assume anything outside DBC is latin-like. I changed the code and it works perfectly for Vietnamese 😃

**Review by avaris — APPROVED** [review]
Thanks!

**Comment by justinmayer** [comment]
Many thanks to @manhhomienbienthuy for the enhancement and to @avaris for reviewing. 🏅

**Pull request merged**
