### PR TITLE
Fix LOG_FILTER to act on exact messages

### LINKED ISSUE #2552: LOG_FILTER not working as it should?
Good evening folks,

I have a problem with LOG_FILTER. According to the docs, one can remove `TAG_SAVE_AS is set to False` by configuring `LOG_FILTER` this way:

```python
import logging
LOG_FILTER = [(logging.WARN, 'TAG_SAVE_AS is set to False')]
```

So to ignore `AUTHOR_SAVE_AS is set to False` and `CATEGORY_SAVE_AS is set to False`, it must be :

```python
import logging
LOG_FILTER = [
    (logging.WARN, 'AUTHOR_SAVE_AS is set to False'),
    (logging.WARN, 'CATEGORY_SAVE_AS is set to False')
]
```
Right?

So this is what I did:
```bash
$ head pelicanconf.py -n 20
#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals
import datetime
import logging

import pelican

PELICAN_VERSION = pelican.__version__

[...]

LOG_FILTER = [
    (logging.WARN, 'AUTHOR_SAVE_AS is set to False'),
    (logging.WARN, 'CATEGORY_SAVE_AS is set to False')
]

AUTHOR_SAVE_AS = False
AUTHORS_SAVE_AS = False
TAG_SAVE_AS = False
TAGS_SAVE_AS = False
CATEGORY_SAVE_AS = False
CATEGORIES_SAVE_AS = False
ARCHIVES_SAVE_AS = False

$ make publish
pelican /mnt/c/Users/max/Code/mlcdf/content -o /mnt/c/Users/max/Code/mlcdf/output -s /mnt/c/Users/max/Code/mlcdf/publishconf.py
WARNING: CATEGORY_SAVE_AS is set to False
WARNING: AUTHOR_SAVE_AS is set to False
Done: Processed 2 articles, 0 drafts, 4 pages, 1 hidden page and 0 draft pages in 0.52 seconds.
```
2 things here:
- it didn't work: `AUTHOR_SAVE_AS is set to False` and `CATEGORY_SAVE_AS is set to False` are still logged.
- and, you may have noticed that, despite setting `TAG_SAVE_AS = False`, and not filtering it, I did not see `TAG_SAVE_AS is set to False` in the logs.

Using the template to filter worked (but it will also filter out other logs matching the template which is not what you would necessary want):
```
import logging
LOG_FILTER = [
    (logging.WARN, '%s is set to %s'),
]
```

* Am I missing something?
* What's the intended behaviour here? Is there an actual bug in the code? Or is the code example in the docs just wrong?

I'm a bit lost. 🙃 

Maxime

### PR DESCRIPTION
**Pull request by avaris**
* Adds the ability to filter templated messages by exact message,
as well as templates.
* Adds a test for LimitFilter.

Fixes #2552,  #2682

### CODE REVIEW

**Comment by justinmayer** [comment]
Many thanks for this fix, Deniz. Much appreciated! 🏅

**Comment by jorgesumle** [comment]
How could you filter logs when [you can't guess a template or the exact messages are many and too long](https://github.com/getpelican/pelican-plugins/issues/1300)?

**Comment by avaris** [comment]
Why would you guess when you can [look for the template](https://github.com/getpelican/pelican/search?q="original+(not+translated)+items")?

**Comment by jorgesumle** [comment]
> we can change that to be a proper template.

The files affected can be 2, 3, 4, 5..., it's not possible. We could add a regex filter, but I don't think it's worth changing Pelican code (it's just a warning related to a plugin). The plugin cannot be easily reprogrammed, because it works by changing the `SITEURL` for every subsite. I finally gave up and simply commented the lines of code of the warning in my local Pelican version.

**Comment by avaris** [comment]
Why would it be "not possible"? Instead of adding N times `'\n%s'` to the template and passing file names individually, it can pre-format file names (`'\n'.join(file_names)`) and have a single `%s` in the template for that ([like this](https://github.com/getpelican/pelican/blob/7a6686f4679adabdd690668a4ba7cedaf494e243/pelican/server.py#L86-L88)).

And, it does worth changing. You provided the reason :). It makes a feature (`LOG_FILTER`) not feasible.

Now, whether or not this should be automatically filtered in the plugin is another matter. Filtering every warning like this is a bit like "nuclear option". Should be left as a last resort and used only if plugin cannot be refactored to produce warning free output.

**Pull request merged**
