### PR TITLE
Add categories.html template to default theme. Fixes #2972

### LINKED ISSUE #2972: Categories template missing in notmyidea theme
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Ubuntu 21.10
- **Python version**: 3.9.7
- **Pelican version**: 4.7.1
- **Link to theme**: 'notmyidea'
- **Links to plugins**: None
- **Link to your site**: 
- **Link to your source**: 
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: 

## Issue
 The official theme 'notmyidea' don't have a `categories.html` and render a 'broken' UI.

### PR DESCRIPTION
**Pull request by pauloxnet**
# Pull Request Checklist

Resolves: #2972

- [x] Ensured **tests pass** and (if applicable) updated functional test output
- [x] Conformed to **code style guidelines** by running appropriate linting tools
- [x] Added **tests** for changed code
- [ ] Updated **documentation** for changed code

### CODE REVIEW

**Comment by pauloxnet** [comment]
Tests failure seems unrelated to the commit.

**Comment by justinmayer** [comment]
Hi Paolo. 👋  It seems to me that the [test failure](https://github.com/getpelican/pelican/runs/4795846772?check_suite_focus=true#step:11:191) is happening because the functional test output was not updated to match the changes in this PR. Did you follow all the steps in the [Development](https://docs.getpelican.com/en/latest/contribute.html#development) section of the docs?

**Comment by pauloxnet** [comment]
Thanks for the feedback. I'll check it again tomorrow.

**Comment by pauloxnet** [comment]
@justinmayer thanks again for the feedback. I updated some test to match the fixed categories template. Now all tests pass.

**Comment by pauloxnet** [comment]
Can some mantainer review and merge or close this PR ?

**Comment by justinmayer** [comment]
@pauloxnet: Thank you for updating the functional test output.

@getpelican/reviewers: Any final comments on this pull request before it is merged?

**Comment by justinmayer** [comment]
Many thanks for the enhancement, Paolo! On a side note, for most contributions to Pelican, you can omit filing an issue + PR and instead simply submit a PR by itself. One less thing to keep track of. 😊

**Pull request merged**
