### PR TITLE
Replace Fabric with Invoke

### PR DESCRIPTION
**Pull request by kdeldycke**
The current ``fabfile.py`` template was design for Fabric 1.x and no longer work with Fabric 2.x.

Most of the utilities and methods we were using have been deprecated or removed entirely: http://docs.fabfile.org/en/latest/upgrading.html

Under the hood, all the machinery to automate tasks in Fabric 1.x has been moved to the new [Invoke project](http://www.pyinvoke.org/). Fabric 2.x is now focused on parallel remote execution, and is using Invoke behind the scene.

Which means we can use Invoke instead to automate our tasks. That's the purpose of that PR.

### CODE REVIEW

**Comment by justinmayer** [comment]
@kdeldycke: Would you take a look and resolve the merge conflicts so we can merge your pull request?

**Comment by kdeldycke** [comment]
All merge conflicts have been resolved, the PR is ready to be merged.

**Comment by justinmayer** [comment]
Many thanks to @kdeldycke for the contribution and to @jonathan-s and @avaris for reviewing.

**Comment by justinmayer** [comment]
Merged via c04a4701b88a56248a0130d09583ee850a23cc6b. 🚀

**Comment by kdeldycke** [comment]
Thanks for the merge! 😃

**Pull request closed without merging**
