### PR TITLE
Update python test versions

### PR DESCRIPTION
**Pull request by lioman**
- add 3.12
- remove 3.7 since it is out of support
- use 3.11 as stable base version for linter and docs

# Pull Request Checklist

Resolves: #issue-number-here 

- [ ] Ensured **tests pass** and (if applicable) updated functional test output
- [ ] Conformed to **code style guidelines** by running appropriate linting tools
- [ ] Added **tests** for changed code
- [ ] Updated **documentation** for changed code

### CODE REVIEW

**Comment by lioman** [comment]
Ok this pr is probably a bit ahead of time. 3.12 is just released and GitHub has not updated their available python versions yet.

**Comment by pauloxnet** [comment]
It can be better to have two separate PRs: one to remove outdated Python versions and one to add Python 3.12 support (which maybe Github will provide in the meantime).

**Comment by justinmayer** [comment]
We should probably also remove all other references to Python 3.7. Some of the ones I found are:

- setup.py
- pyproject.toml
- docs/contribute.rst
- docs/install.rst
- docs/quickstart.rst

Regarding the latter three places in the docs, I think we should choose *one* canonical place to document the minimum supported Python version, and then link to that from other places so that every time a Python version goes EOL we can minimize the number of changes we have to make.

**Comment by lioman** [comment]
Good idea - I will try to get this done

**Comment by lioman** [comment]
I close this in favor of #3199 and another yet to be created one

**Pull request closed without merging**
