### PR TITLE
Add python 3.6 in tox.ini

### PR DESCRIPTION
**Pull request by farseerfc**
Python 3.6 is now released, this change added python3.6 in tox.ini

### CODE REVIEW

**Comment by andriisoldatenko** [comment]
@farseerfc What about update in all places?
E.g. https://github.com/getpelican/pelican/blob/master/.travis.yml

**Comment by farseerfc** [comment]
Sorry I didn't add travis config. I don't know when travis will support python 3.6

**Comment by ingwinlu** [comment]
Hi, travis already supports it in their own weird way that does not play that nice with our setup. 

See #2094 for a complete update.

**Comment by farseerfc** [comment]
@ingwinlu hi, thanks for telling me!

**Pull request closed without merging**
