### PR TITLE
Add DISPLAY_TAGS_ON_MENU option (Fix #2244)

### LINKED ISSUE #2244: Missing DISPLAY_TAGS_ON_MENU option
There is the two options:
DISPLAY_PAGES_ON_MENU
DISPLAY_CATEGORIES_ON_MENU

But the DISPLAY_TAGS_ON_MENU option is missing.

The [pelican-twitchy](https://github.com/ingwinlu/pelican-twitchy) theme has implemented it, but it should be a Pelican built-in.

### PR DESCRIPTION
**Pull request by fgallaire**

### CODE REVIEW

**Comment by fgallaire** [comment]
Travis flake8 job fails because of import order in pelican/__init__.py unrelated to this.

**Comment by ssteinerx** [comment]
@fgallaire In  https://github.com/getpelican/pelican/pull/2246#issuecomment-342467973

There's a note about the import order issue: "I addressed the flake8-import-order issue via 8ebc120, so all lights are green here now. 🎉"

If you pull those changes forward this may clear the travis hurdle.

**Comment by fgallaire** [comment]
Done, thanks @ssteinerx

**Comment by justinmayer** [comment]
As noted in the corresponding issue, the stated motivation behind adding a `DISPLAY_TAGS_ON_MENU` setting was to work around the (intentional) inability to assign multiple categories to a post. Since there is now a [More Categories](DISPLAY_TAGS_ON_MENU) plugin that provides that ability, there does not seem to be much reason to proceed with adding a `DISPLAY_TAGS_ON_MENU` setting at this time.

**Pull request closed without merging**
