### PR TITLE
Don't fail if --fatal not provided

### PR DESCRIPTION
**Pull request by kernc**
Fixes https://github.com/getpelican/pelican/issues/1891

Sorry.

### CODE REVIEW

**Comment by justinmayer** [comment]
@kernc: Looks like there are some test failures here.

**Comment by ingwinlu** [comment]
NO, fix the design, don't hack a solution.

**Comment by kernc** [comment]
Got it, I set the argparser's `default=''`. `ArgumentDefaultsHelpFormatter` now prints `(default: )` which isn't far from truth anyway.

I don't understand why the build is failing, though. Doesn't seem related.

**Comment by avaris** [comment]
Build is failing because Pygments recently released a [new version (2.1)](https://pypi.python.org/pypi/Pygments/2.1) and the output is somehow different than the previous one (2.0.2). So yeah, it's not related to this PR. We probably need to update our test output before any other PR.

**Comment by ingwinlu** [comment]
while this would fix the issue I would rather see a different approach:

introduce log.FATAL = 0,1,2 where 0 is for nothing, 1 is for errors, 2 is for warnings; or similar.

I do not like comparing strings in that use case. If you do not want to do it that way this will do in the meantime.

**Comment by justinmayer** [comment]
Merging this for now.

@kernc: Would you perhaps consider a follow-up pull request that implements @ingwinlu's suggested approach?

**Comment by kernc** [comment]
I was amazed how tolerant you were of this failing. :smiley: 

I didn't quite _get_ @ingwinlu's suggestion; why would one wish to complicate stuff by introducing a lookup table instead of using the (only) two booleans that make sense?

**Pull request merged**
