### PR TITLE
Server: limit logging when resolving get request

### PR DESCRIPTION
**Pull request by oulenz**
Fixes https://github.com/getpelican/pelican/issues/2456 (hopefully)

### CODE REVIEW

**Comment by justinmayer** [comment]
Many thanks, @oulenz!

Any comments from @getpelican/reviewers on this proposed fix?

**Comment by justinmayer** [comment]
@oulenz: Do you feel like anything from this PR is still relevant now that the one @avaris submitted has been merged?

**Comment by mosra** [comment]
I *think* this could still reduce the logging on failure (the list of attempted tries would be shorter for paths that are directories), but it's such a rare corner case that I'm not sure is worth the extra complexity.

**Comment by oulenz** [comment]
As far as I am concerned this is now purely cosmetic, so I'll close.

**Pull request closed without merging**
