### PR TITLE
Fix broken links from documentation

### PR DESCRIPTION
**Pull request by jorgesumle**
Solves #2301

### CODE REVIEW

**Comment by ingwinlu** [comment]
@justinmayer ping

**Comment by justinmayer** [comment]
Many thanks to @jorgesumle for the contribution and to @ingwinlu for the review. 🎊

**Comment by jorgesumle** [comment]
Don't forget to close #2301 

I can't do it because I didn't open it, and I'm just a contributor.

**Comment by avaris** [comment]
@jorgesumle You managed to find the gap in github :). For future reference: [Closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)

**Comment by justinmayer** [comment]
@jorgesumle: Closed it. Thanks for the reminder.

**Comment by jonathan-s** [comment]
closes #2282

**Pull request merged**
