### PR TITLE
Add a new signal: page_writer_finalized

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by justinmayer** [comment]
Hi Julien. Very sorry for the long delay in getting back to you. [Another commit was merged recently](https://github.com/getpelican/pelican/commit/265f68a879b7d2b1cc5d611f7998ace07ee4d608) that may or may not provide similar functionality. Would you please take a look and let us know whether you think your contribution is still required?

**Comment by roidelapluie** [comment]
@justinmayer it is still required to get the feed as parameter of the hook

**Comment by roidelapluie** [comment]
@justinmayer any news?

**Comment by justinmayer** [comment]
Apologies for the extended delay, Julien. Thank you for the contribution.

**Comment by roidelapluie** [comment]
It is fine. Please continue to make pelican the better static site generator out there :)

**Pull request merged**
