### PR TITLE
Localize default lang and timezone in pelican-quickstart

### LINKED ISSUE #1971: Localize defaults in pelican-quickstart
Now, default language and timezone are hard-coded ('en', 'Europe/Paris').
Use system locale to adjust default values.

### PR DESCRIPTION
**Pull request by nstinus**
Fixes #1971.

### CODE REVIEW

**Comment by avaris** [comment]
You need to somehow inform the user about the new optional dependency (`tzlocal`).

**Comment by nstinus** [comment]
You are right, I thought about it too.
I'll have a look at my options.

**Comment by nstinus** [comment]
Hi,

Either I add tzlocal as a hard requirement, which I don't really like.
Or I use extra_requires
<http://peak.telecommunity.com/DevCenter/setuptools#declaring-extras-optional-features-with-their-own-dependencies>
from
setuptools, which does not seem to be user- but more dev-oriented.

As far as I an tell, there is nothing lke this:
The Markdown module is optional and yet, I don't think it is advertised as
such anywhere.

Nicolas

**Comment by avaris** [comment]
Markdown is stated [here](http://docs.getpelican.com/en/3.6.3/install.html#optional-packages).

If you like, you can create a note at the end of [here](http://docs.getpelican.com/en/3.6.3/quickstart.html#create-a-project).

**Comment by nstinus** [comment]
I didn't search the docs but the source ;)
As suggested, I added a footnote in quickstart's doc.

**Comment by leotrs** [comment]
Looks good to me.

**Comment by justinmayer** [comment]
Thanks for the contribution, Nicolas. Do you think it makes sense to add test(s) for these additions? Also, once done, please [rebase & squash your commits](https://github.com/getpelican/pelican/wiki/Git-Tips#squashing-commits).

**Comment by justinmayer** [comment]
Hi @nstinus. Just checking in regarding my last comment. Have a moment to respond so we can get this merged?

**Comment by nstinus** [comment]
@justinmayer: I don't really see the point of adding tests for that.

**Comment by justinmayer** [comment]
Thanks for the enhancement, Nicolas.

**Pull request merged**
