### PR TITLE
Remove duplicate tags

### PR DESCRIPTION
**Pull request by fernandezcuesta**
When a tag is entered more than once in metadata, pelican should discard duplicates. Same when there's no tag at all.

### CODE REVIEW

**Comment by ingwinlu** [comment]
might be better to handle this case at https://github.com/getpelican/pelican/blob/master/pelican/readers.py#L258 , so it has the same behaviour for any listed metadata

**Comment by fernandezcuesta** [comment]
Just modified https://github.com/getpelican/pelican/blob/master/pelican/readers.py#L34 which applies as well to any listed metadata.

**Comment by avaris** [comment]
Tests are failing because of the semi-random behavior of the `set` order. Might be better to use `OrderedDict`.

**Comment by ingwinlu** [comment]
please look at http://pelican.readthedocs.org/en/latest/contribute.html#using-git-and-github and squash your commits

**Comment by justinmayer** [comment]
Hi @fernandezcuesta. Would you please take a look at the comments on your pull request and make the relevant changes so we can get your contribution merged?

**Comment by fernandezcuesta** [comment]
@justinmayer you may drop it, the fix is already achieved in c9183808021e54aa9b949939ff289b07c4443b7e

**Pull request closed without merging**
