### PR TITLE
Nitpick Content decorators

### PR DESCRIPTION
**Pull request by syndbg**
A bit more readable this way.

### CODE REVIEW

**Comment by avaris** [comment]
... and broken :)

`get_url_setting` -> `self.get_url_setting`

**Comment by iKevinY** [comment]
Which, not to mention, is even *more* readable!

**Comment by syndbg** [comment]
@avaris Oopsie-daisies. Tried my best with the online Github editor. 

Fixing stuff and cherry picking now.

**Comment by syndbg** [comment]
Sorry for the lack of updates, busy week here. 

Thanks @avaris and @zackw for the guidance.

**Comment by justinmayer** [comment]
@avaris / @iKevinY: Any comments on the latest iteration here?

**Comment by iKevinY** [comment]
Looks good to merge to me. (Thanks for removing that pesky trailing space, @syndbg.)

**Comment by justinmayer** [comment]
Thanks for the contribution and the review!

**Pull request merged**
