### PR TITLE
WP import: Category is categories[0]

### PR DESCRIPTION
**Pull request by fgallaire**
Same behaviour as --dir-cat
Fix part of #2239

### CODE REVIEW

**Comment by ssteinerx** [comment]
I haven't looked at the code but, assuming this once worked, is `categories` always a list or can it be a string if there's only one?

Also, is there a test that fails with current code, but passes with new?

**Comment by fgallaire** [comment]
I modify nothing, ``categories`` is still the list of the wordpress categories of the post and I only take the first category to become the pelican "who only supports one category by design" category.
This is the same behaviour as the --dir-cat option, making the whole coherent.

**Comment by fgallaire** [comment]
Needed to avoid the creation of list categories nobody wants as import result:

```
Documentation (2)
Documentation, Media (1)
Documentation, Site (2)
Documentation, Tools (1)
Documentation, Translations (13)
```

**Comment by justinmayer** [comment]
@fgallaire: Many thanks for the contribution, Florent. My apologies for the long delay. I think perhaps the plugin that @oulenz documented in #2434 obviates the need to make changes to how multiple categories are handled by the WP importer in Pelican core. That said, if you still feel further changes in core are warranted, please comment here and we can re-open. Thanks again! 😅

**Pull request closed without merging**
