### PR TITLE
When truncating, consider hyphens, apostrophes and HTML entities.

### PR DESCRIPTION
**Pull request by andreacorbellini**
Thanks for approving my last PR.

Here's a new one: this code avoids truncating words like "it's", "here's" or "caf&egrave;".

When this PR gets merged, I'll create a new one for improving the speed of `_HTMLWordTruncator`.

### CODE REVIEW

**Comment by justinmayer** [comment]
Hey Andrea. Thanks for the contribution. It looks like there are test failures. Would you mind investigating and resolving?

**Comment by andreacorbellini** [comment]
OK, I was missing the French locale (hence those tests were skipped on my machine). Now everything should work as expected.

**Comment by justinmayer** [comment]
Hi Andrea. Thanks for addressing the locale issue. Having just merged a pull request that enforces PEP8 compliance, most outstanding pull requests (including yours) will need to be rebased on current master before they can be merged. Would you please rebase+squash your commits so I can merge your contribution?

I'm sorry for the extra effort this imposes upon you and appreciate your understanding.  (^_^)

**Comment by andreacorbellini** [comment]
There you go!

**Comment by justinmayer** [comment]
Thanks for the contribution, Andrea!

**Comment by justinmayer** [comment]
Hi @andreacorbellini. I just noticed that this commit appears to have introduced an error when generating my site ([traceback](https://dpaste.de/V1dU)). Is something you might be able to look into?

**Comment by andreacorbellini** [comment]
I'll look into it as soon as possible. (I'll also add some tests.)

**Pull request merged**
