### PR TITLE
Expose first and last page of pagination

### PR DESCRIPTION
**Pull request by jlusiardi**
Implements a *_first_page and *_last_page for all paginable objects.
These can be used fo jump to first and last pages.

### CODE REVIEW

**Comment by avaris** [comment]
Code looks good, but it's relatively simple enough that I'm inclined to leave it to be done in the template when needed:

```jinja2
{% set first_page = articles_paginator.page(1) %}
{% set last_page = articles_paginator.page(articles_paginator.num_pages) %}
```

**Comment by jlusiardi** [comment]
so we could change the `pagination.html` template to 

```
{% if DEFAULT_PAGINATION %}
{% set first_page = articles_paginator.page(1) %}
{% set last_page = articles_paginator.page(articles_paginator.num_pages) %}
<p class="paginator">
    {% if articles_page.has_previous() %}
        <a href="{{ SITEURL }}/{{ first_page.url }}">&#8647;</a>
        <a href="{{ SITEURL }}/{{ articles_previous_page.url }}">&#8592;</a>
    {% endif %}
    Seite {{ articles_page.number }} von {{ articles_paginator.num_pages }}
    {% if articles_page.has_next() %}
        <a href="{{ SITEURL }}/{{ articles_next_page.url }}">&#8594;</a>
        <a href="{{ SITEURL }}/{{ last_page.url }}">&#8649;</a>
    {% endif %}
</p>
{% endif %}
```

**Comment by justinmayer** [comment]
Hi Joachim. Thank you for your pull request. Would you be willing to reformulate it to instead consist of changes to the `pagination.html` template, as noted above?

**Comment by jlusiardi** [comment]
Hi Justin, 

I hope I changed the PR according to the requirements, wasn't quite aware this was still open ;)
Not sure why the checks fail though...

**Comment by justinmayer** [comment]
@avaris: Would you mind taking a moment to review the latest iteration of this PR?

**Comment by justinmayer** [comment]
Many thanks to @jlusiardi for the contribution and to @avaris for reviewing. 👯‍♂️

**Comment by jlusiardi** [comment]
Cool thanks guys!

**Pull request merged**
