### PR TITLE
Add internal link translation for srcset attribute in HTML5 picture tag 

### PR DESCRIPTION
**Pull request by maherma-adg**

### CODE REVIEW

**Comment by justinmayer** [comment]
Any comments from @getpelican/reviewers?

**Comment by ingwinlu** [comment]
lgtm if squashed

**Comment by maherma-adg** [comment]
how can I do it from github?

**Comment by justinmayer** [comment]
@maherma-adg: https://github.com/getpelican/pelican/wiki/Git-Tips

**Comment by avaris** [comment]
I'm a little confused. Isn't `srcset` usually contains a bunch of links? And isn't it often accompanied by a `src` attribute as a fallback? I don't think either of them will work here. Granted, the regex isn't built for this, but this looks like a buggy "feature" to me.

**Comment by justinmayer** [comment]
Many thanks for your contribution, @maherma-adg. Since this pull request never quite made it to the level we need it to be for inclusion into Pelican master, for now I think it's best to close it. If you would like to work on this endeavor further, please submit an issue so we can discuss.

**Comment by sqwishy** [comment]
What the fuck? What level does this need to be at for it to be included into Pelican master?

**Pull request closed without merging**
